### ISSUE TITLE
Some ability bugs, mostly ATK49 related

### ISSUE THREAD

**Issue by Squeetz** [DizzyEggg/pokeemerald#106]
ABILITY_IMPOSTER:
    check if opposite battler is semi invulnerable
ABILITY_DEFIANT:
ABILITY_COMPETITIVE:
    the way these were implemented makes it impossible to check if the battler's stat was lowered by itself/its ally or an opponent (defiant/competitive wont activate in the former case)
ABILITY_CURSED_BODY:
    GetBattleMonMoveSlot(&gBattleMons[gBattlerAttacker], gChosenMove) is completely unecessary, just read from gChosenMovePos
    also check if the chosen move has pp left
ABILITY_ANGER_POINT:
    manually setting sB_ANIM_ARG1 to the chosen stat animation will not be indicative of amount of stages raised, i suggest adding 'setgraphicalstatchangevalues' to the script and setting gBattleScripting.statChanger to '12 - gBattleMons[battler].statStages[STAT_ATK] then | STAT_ATTACK'
    nitpick: wrong name for battle script & string: "angrypoint"
ABILITY_JUSTIFIED:
ABILITY_RATTLED:
    you forgot to buffer the stat to change, either call ChangeStatBuffs or use PREPARE_STAT_BUFFER
ABILITY_WEAK_ARMOR:
    check if the current move is physical (weak armor only activates on physical hits)
    speed should raise by 2, not 1

**Comment by DizzyEggg** [comment]
Imposter: Can't find info that it checks for semi invulnerable anywhere on Bulbapedia and Smogon.

Defiant/Competitive: It doesn't raise stats if the pokemon lowered them by self, but you're right about no ally check. Not-sure-how-to-feel-about-it fix at  701874523

Cursed Body: d1fb5fa14 Why would I check for no pp tho?

Anger Point: e135ea47e

Justified/Rattled: b9052fb37

Weak Armor: b8a634770

**Comment by DizzyEggg** [comment]
Imposter: e2268bd93

Cursed Body PP check: 86e8bf0ec
