### ISSUE TITLE
Seed Flare has the wrong effect

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#155]
Because it has EFFECT_SPECIAL_DEFENSE_DOWN_2, it cannot work as the offensive move that it's supposed to be.
I guess someone will have to make a EFFECT_SPECIAL_DEFENSE_DOWN_HIT_2 or something like that, unless there's already a hold effect here that can cover it.

**Comment by DizzyEggg** [comment]
e9829c16c
