### ISSUE TITLE
Synchronize + Toxic Causes Issues

### ISSUE THREAD

**Issue by Kurausukun** [DizzyEggg/pokeemerald#161]
If you use Toxic and it gets reflected by an opponent's Synchronize, instead of the opponent's "synchronize" card popping up, YOUR ability card pops up, and whatever string happened to occupy the last string variables gets used instead of the ability; e.g. "{Pokemon} was poisoned by foe {Pokemon's} evasiveness" was an example I got.

**Comment by DizzyEggg** [comment]
48c801245
