### ISSUE TITLE
Debug menu should only appear if building ROM as debug.

### ISSUE THREAD

**Issue by Gamer2020** [DizzyEggg/pokeemerald#167]
Currently the in battle debug menu is usable no matter how you build the ROM. Perhaps it can be made so that menu is only used if the ROM is built with DINFO=1?

**Comment by DizzyEggg** [comment]
If you set USE_BATTLE_DEBUG in battle_debug.h to false, it won't be.

**Comment by Gamer2020** [comment]
Ah didn't see that, thanks!

Get Outlook for Android
