### ISSUE TITLE
Finish all move animations on battle_engine_v2

### ISSUE THREAD

**Issue by Xhyzi** [DizzyEggg/pokeemerald#171]
This is a list with the current state of every new animation of the battle_engine_v2.

******** 4TH GEN ATTACKS *********

- [x] - Magnet Bomb       
- [x] - Iron Head         
- [x] - Mirror Shot       
- [x] - Flash Cannon      
- [x] - Gyro Ball         
- [x] - Bullet Punch      
- [x] - Metal Burst       
- [x] - Aqua Ring         
- [x] - Aqua Tail         
- [x] - Aqua Jet          
- [x] - Brine             
- [x] - Defend Order      
- [x] - Attack Order      
- [x] - Heal Order        
- [x] - U-Turn            
- [x] - Bug Bite          
- [x] - X-Scissor         
- [x] - Bug Buzz          
- [x] - Dragon Rush       
- [x] - Draco Meteor      
- [x] - Spacial Rend     
- [x] - Roar Of Time      
- [x] - Dragon Pulse      
- [x] - Discharge          
- [x] - Thunder Fang      
- [x] - Magnet Rise       
- [x] - Charge Beam        - TODO: Maybe try new particles(?)
- [x] - Shadow Claw       
- [x] - Shadow Force      
- [x] - Shadow Sneak      
- [x] - Ominous Wind      
- [x] - Fire Fang         
- [x] - Flare Blitz       
- [x] - Lava Plume        
- [x] - Magma Storm        
- [x] - Avalanche          - TODO: New particles & sound(?)
- [x] - Ice Shard         
- [x] - Ice Fang          
- [x] - Close Combat      
- [x] - Aura Sphere        - TODO: Change particle (this one is too generic)
- [x] - Wake-up Slap      
- [x] - Hammer Arm        
- [x] - Focus Blast       
- [x] - Vacumm Wave        
- [x] - Force Palm        
- [x] - Drain Punch       
- [x] - Acupressure         
- [x] - Crush Grip        	
- [x] - Feint              
- [x] - Trump Card         
- [x] - Lucky Chant       
- [x] - Copycat           
- [x] - Double Hit        
- [x] - Natural Gift      
- [x] - Wring Out         	 
- [x] - Giga Impact       	
- [x] - Captivate         
- [x] - Judgement         
- [x] - Rock Climb        
- [x] - Last Resort       
- [ ] - Me First          
- [x] - Worry Seed         
- [x] - Seed Bomb         
- [x] - Energy Ball       
- [x] - Seed Flare        
- [x] - Grass Knot        
- [x] - Power Whip        
- [x] - Leaf Storm        
- [x] - Wood Hammer       
- [x] - Heal Block        
- [x] - Zen Headbutt      
- [ ] - Heart Swap       
- [x] - Guard Swap        
- [x] - Power Swap        
- [x] - Lunar Dance       
- [x] - Healing Wish      
- [x] - Trick Room        
- [x] - Miracle Eye       
- [x] - Gravity           
- [x] - Psycho Shift      			
- [x] - Psycho Cut        
- [x] - Power Trick       
- [x] - Power Gem         
- [x] - Rock Polish       
- [x] - Stone Edge        
- [x] - Rock Wrecker      
- [x] - Head Smash        
- [x] - Stealth Rock       
- [x] - Dark Void        
- [x] - Assurance         
- [x] - Punishment        
- [x] - Embargo           
- [x] - Sucker Punch      	
- [x] - Fling             
- [x] - Nasty Plot        
- [x] - Dark Pulse        
- [x] - Night Slash       
- [x] - Switcheroo        
- [x] - Payback           
- [x] - Mud Bomb          
- [x] - Earth Power        
- [x] - Gastro Acid       		
- [x] - Gunk Shot         
- [x] - Toxic Spikes      
- [x] - Poison Jab        
- [x] - Cross Poision     
- [x] - Chatter           
- [x] - Defog             
- [x] - Brave Bird        
- [x] - Pluck              
- [x] - Roost             			
- [x] - Air Slash         
- [x] - Tailwind   

******** 5TH GEN ATTACKS *********

- [x] - Autotomize	    
- [x] - Shift Gear        
- [x] - Heavy Slam
- [x] - Gear Grind        
- [x] - Scald             
- [x] - Razor Shell       
- [x] - Soak
- [x] - Water Pledge     
- [x] - Rage Powder       
- [x] - Struggle Bug      
- [x] - Quiver Dance 
- [x] - Steamroller
- [x] - Dual Chop         
- [x] - Dragon Tail       
- [x] - Fusion Bolt       
- [x] - Electro Ball      
- [x] - Electro Web       
- [x] - Bolt Strike      
- [x] - Volt Switch 
- [x] - Wild Charge       
- [x] - Hex               
- [x] - Curse             
- [x] - Flame Burst
- [x] - Blue Flare       
- [x] - Fusion Flare      
- [x] - Fiery Dance       
- [x] - Fire Pledge      
- [x] - Searing Shot      
- [x] - Heat Crash        
- [x] - Incinerate        
- [x] - Flame Charge      
- [x] - Inferno
- [x] - V-Create          
- [x] - Ice Burn          
- [x] - Freeze Shock     
- [x] - Glaciate        
- [x] - Frost Breath      
- [x] - Icicle Crash      
- [x] - Final Gambit      
- [x] - Quick Guard       
- [x] - Low Sweep
- [x] - Storm Throw
- [x] - Circle Throw      
- [x] - Sacred Sword      
- [x] - Secret Sword      
- [x] - Round
- [x] - Head Charge       
- [x] - After you         
- [x] - Relic Song      
- [x] - Entrainment      
- [x] - Work Up 
- [x] - Echoed Voice      
- [x] - Bestow            
- [x] - Chip Away         
- [x] - Reflect Type   
- [x] - Retalitate        
- [ ] - Shell Smash       
- [x] - Simple Beam       
- [x] - Tail Slap         
- [x] - Techno Blast     
- [x] - Cotton Guard           
- [x] - Leaf Tornado      
- [x] - Grass Pledge      
- [x] - Horn Leech        
- [x] - Stored Power
- [x] - Guard Split      
- [x] - Heal Pulse
- [x] - Heart Stamp       
- [x] - Magic Room        
- [x] - Power Split      
- [x] - Psystrike
- [x] - Psyshock          
- [ ] - Ally Switch      
- [x] - Sychronoise       
- [x] - Telekinesis      
- [x] - Wonder Room       
- [x] - Smack Down        
- [x] - Wide Guard        
- [x] - Snarl             
- [x] - Hone Claws
- [x] - Night Daze        
- [x] - Quash           
- [x] - Foul Play         
- [x] - Drill Run         
- [x] - Bulldoze          
- [x] - Acid Spray 
- [x] - Clear Smog        
- [x] - Sludge Wave       
- [x] - Coil              
- [x] - Venoshock     
- [x] - Acrobatics
- [x] - Sky Drop          
- [x] - Hurricane         

******** 6TH GEN ATTACKS *********
- [x] - King's Shield     
- [x] - Steam Eruption    
- [x] - Origin Pulse      
- [x] - Water Shuriken 
- [x] - Infestation       
- [x] - Fell Stinger      
- [x] - Powder            
- [x] - Sticky Web        
- [x] - Electric Terrain  
- [x] - Parabolic Charge  
- [ ] - Ion Deluge        
- [x] - Electrify         
- [x] - Nuzzle            
- [x] - Eerie Impulse     
- [x] - Phantom Force 
- [ ] - Trick-or-Treat    
- [x] - Mystical Fire     
- [x] - Sweet Kiss        
- [x] - Draining Kiss     
- [x] - Dazzling Gleam        
- [x] - Misty Terrain     
- [x] - Play Rough        
- [x] - Fairy Lock        
- [x] - FLower Shield     
- [x] - Charm             
- [x] - Moonblast    
- [x] - Geomancy          
- [x] - Light of Ruin     
- [x] - Moonlight         
- [x] - Baby-Doll Eyes    
- [x] - Crafty Shield     
- [x] - Aromatic Mist     
- [x] - Fairy Wind        
- [x] - Disarming Voice   
- [x] - Freeze-Dry        
- [x] - Mat Block        
- [x] - Flying Press      
- [x] - Power-Up Punch    
- [x] - Play Nice         
- [x] - Celebrate        
- [x] - Boomburst      
- [x] - Happy Hour        
- [x] - Noble Roar  
- [x] - Hold Back         
- [x] - Hold Hands       
- [x] - Spiky Shield      
- [x] - Grassy Terrain    
- [x] - Forest's Curse    
- [x] - Petal Blizzard    
- [x] - Hyperspace Hole  
- [x] - Diamon Storm      
- [x] - Hyperspace Fury  
- [x] - Topsy-Turvy      
- [x] - Parting Shot      
- [x] - Rototiller        
- [x] - Precipice Blades  
- [x] - Land's Wrath    
- [x] - Thousand Arrows   
- [x] - Thousand Waves    
- [x] - Belch             
- [x] - Venom Drench      
- [x] - Oblivion Wring    
- [x] - Dragon Ascent

**Comment by DizzyEggg** [comment]
Project moved to RHH
