### ISSUE TITLE
[Bug] Money Branch - Sell Price Display

### ISSUE THREAD

**Issue by sora10pls** [DizzyEggg/pokeemerald#179]
Hey, while I know it's not an actively updated branch, I do appreciate it as it's helped me out with my own ROM hack. But, there is one thing I noticed that doesn't display correctly in-game.

After replicating the changes from https://github.com/DizzyEggg/pokeemerald/commit/aeddcdbfef67788dbadfcde806981d99ae9f7be2, I noticed that the sell price in Marts does not display correctly. The last digit in the sell price is cut off completely when the following line is edited (change 6 to 7):
https://github.com/DizzyEggg/pokeemerald/blob/aeddcdbfef67788dbadfcde806981d99ae9f7be2/src/money.c#L145
![pokeemerald-1](https://user-images.githubusercontent.com/17801814/61722764-e0097200-ad38-11e9-8033-e1b1c7415b05.png)
Max Repels sell for $350 ($700 / 2), not $35.

However, if the line is preserved to read `strLength = 6 - StringLength(gStringVar1);`, then the sell price is fixed but it then messes up the moneybox display, not being fully right-aligned and not displaying 7 digits worth of money.

Honestly unsure if you're interested in resolving this issue, but I wanted to bring attention to it just in case. Thanks again!

**Comment by DizzyEggg** [comment]
Thanks for letting me know, I'll investigate it

**Comment by DizzyEggg** [comment]
I did some quick testing and 29d59c3c6 seems to fix the issues you mentioned. Please re-open, if you find your issue was not resolved.

**Comment by sora10pls** [comment]
Can confirm that this did fix the issue, thank you. Would be appreciated for other users if you updated this post on the PokeCommunity forums :) https://www.pokecommunity.com/showpost.php?p=9986063&postcount=10
