### ISSUE TITLE
Some item data is missing.

### ISSUE THREAD

**Issue by Gamer2020** [DizzyEggg/pokeemerald#193]
In the item expansion repo it seems that there is missing data for some items. Below are the ones I have found to be missing.

#define ITEM_SPORT_BALL 23
#define ITEM_PARK_BALL 24
#define ITEM_DREAM_BALL 25
#define ITEM_BEAST_BALL 26
#define ITEM_MICLE_BERRY 204

**Comment by DizzyEggg** [comment]
#199
