### ISSUE TITLE
[Help] Merge your branches

### ISSUE THREAD

**Issue by Dokman** [DizzyEggg/pokeemerald#205]
Hello i want to merge your new battle system with the pokemon expansion but with a Diff tool i can't notice what's wrong and i don't have any IDE to see what code is bad how i can do it? any advice?

**Comment by DizzyEggg** [comment]
Download Notepad++ and follow these steps 
https://www.pokecommunity.com/showpost.php?p=10079378&postcount=75
https://www.pokecommunity.com/showpost.php?p=10029240&postcount=36

**Comment by Dokman** [comment]
thanks for the advice hahahaha
