### ISSUE TITLE
Berserk isn't implemented/Aurora Veil is malfunctioning

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#207]
Berserk has constants and description, but isn't coded into the battle engine.
Aurora Veil works even if the weather is not WEATHER_HAIL_ANY.

**Comment by DizzyEggg** [comment]
Aurora Veil fix - ea9109943
Berserk I'll do some other time 😛

**Comment by DizzyEggg** [comment]
Berserk - 8f61445df
