### ISSUE TITLE
Pokemon front pic does not update in pokemon storage.

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#217]
When looking at pokemon in the pc, the front pic does not update. And example can be seen here:
https://i.imgur.com/tDCdXUc.gifv
additionally, there's a few frames of lag when changing boxes.

**Comment by LOuroboros** [comment]
Can't replicate. Tested the latest commits of the battle_engine_v2 and the pokemon_expansion branches separately.
![2019-12-22_22-10-28](https://user-images.githubusercontent.com/4485172/71330225-73261e00-250a-11ea-8132-cb4327c47263.gif)
![2019-12-22_22-33-51](https://user-images.githubusercontent.com/4485172/71330227-73261e00-250a-11ea-90d0-5858d266c7ca.gif)
