### ISSUE TITLE
[battle_engine_v2] Party menu broken?

### ISSUE THREAD

**Issue by segabl** [DizzyEggg/pokeemerald#220]
When opening the party menu and trying to view a pokemon, nothing happens when pressing A on them, the usual actions menu doesnt show up. they can be viewed in the pc box though.

**Comment by DizzyEggg** [comment]
Cannot reproduce, could you give more info?

**Comment by segabl** [comment]
I just grabbed the project from GitHub and compiled it with default settings, which resulted in me not being able to open the stat screen (or do anything really) from within the party menu.

**Comment by DizzyEggg** [comment]
Both in battle and in overworld?

**Comment by segabl** [comment]
Yes. The menu that would show up when pressing A on a pokemon which lets you select what to do with it (summary, switch, item etc) doesnt show up at all. it should be noted that it works fine if I compile the original source (i.e. the master branch)

**Comment by segabl** [comment]
After another test it seems that VBA is the culprit, as it works in other emulators

**Comment by LOuroboros** [comment]
I tested the latest commit yesterday on VBAM SVN r878 which is the version I regularly use, and everything worked normally.
https://streamable.com/xl1pi

I tested it just now with VBA Link v1.7.2 and VBA Link v1.8.0 and the ROM seems to be working normally on them as well.
![VisualBoyAdvance-2019-12-29_19-46-45](https://user-images.githubusercontent.com/4485172/71563795-4a56d900-2a74-11ea-8d16-11292be65e35.png)
![VisualBoyAdvance-2019-12-29_19-48-12](https://user-images.githubusercontent.com/4485172/71563796-4aef6f80-2a74-11ea-8ac4-6949c7b669a9.png)

**Comment by segabl** [comment]
it might just be a problem with vbam on linux then. anyways, it's solved for me
