### ISSUE TITLE
Fainted mon in front of party gets sent out in special multi battle.

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#221]
If you have a fainted mon at the front of your party, and start a special battle multi(Player + AI vs one opponent), it sends out your fainted mon. This alone isn't that bad as it faints as soon as its turn starts.

Will provide code upon request if needed.

**Comment by Ryuhouji** [comment]
Additionally, not sure if this is due to my configuration or not, but if you lose the battle, it continues script as if you won, doesn't seem to have a defeat condition.

**Comment by DizzyEggg** [comment]
The defeat condition has to be provided by the user in a script. The fainted mon thing needs to be fixed tho.

**Comment by DizzyEggg** [comment]
Alright, so the way it currently works it has to be done this way. If you don't want fainted mons, you'll need to either use the second script variant, where the user is prompted to select mons they with to battle wish. Or create a function, use some existing ones to sort the mons, so the alive mons are at the party's beginning.
