### ISSUE TITLE
Encore causes target to hit itself

### ISSUE THREAD

**Issue by segabl** [DizzyEggg/pokeemerald#222]
If a pokemon on your team is targeted with encore it will use the last used move on itself, for example my whismur used pound against a minun and it used encore on my whismur afterwards, then in the next turns whismur will use pound against itself.

**Comment by segabl** [comment]
I should add that it doesn't seem to always happen. It happened to me in a whismur vs minun trainer battle but later in a wild battle where I used a oddish against a minun it didn't happen.

**Comment by DizzyEggg** [comment]
You are right, I run a quick test, and it seems to indeed happen, albeit rarely. Will fix soon

**Comment by DizzyEggg** [comment]
770a57bec
