### ISSUE TITLE
[battle_engine_v2] The BattleString for Steadfast is incorrect

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#228]
![2020-01-03_12-12-51](https://user-images.githubusercontent.com/4485172/71730998-649d0800-2e22-11ea-8bd8-75738befca17.gif)

To test this I:
-Cloned the battle_engine_v2
-Gave ABILITY_STEADFAST and MOVE_COUNTER to Torchic
-Set Wurmple as the only encounter in Route 101 and gave it Bite as its only known move
-Modified Bite's SecondaryEffectChance from 30 to 100

**Comment by DizzyEggg** [comment]
952bdbd9f
