### ISSUE TITLE
Imposter still shows 'Zoroark'

### ISSUE THREAD

**Issue by RyuTheBoss** [DizzyEggg/pokeemerald#231]
When an ai sends out zoroark, it shows the appearance of another mon in their party, but it still says "X Sent out Zoroark!"
screenshot:
https://i.imgur.com/SZXEmeO.gif

**Comment by AsparagusEduardo** [comment]
Are you sure you don't mean Illusion instead of Imposter?
Imposter is Ditto's hidden ability

**Comment by Ryuhouji** [comment]
You know what I meant, and there's image proof. Words ain't my strong suit...

**Comment by Ryuhouji** [comment]
um... Bump? The game gives away Zoroark by sayin {OPPONENT} sent out Zoroark!
but the _Illusion_ ability works fine otherwise.

**Comment by DizzyEggg** [comment]
The same as #298 Will be fixed soon
