### ISSUE TITLE
AI doesn't always prioritize Fake out on first turn.

### ISSUE THREAD

**Issue by ExoryxHana** [DizzyEggg/pokeemerald#233]

**Comment by segabl** [comment]
this could probably be improved by changing the ai script for fake out
currently it's only
```
AI_CV_FakeOut:
	score +2
	end
```
I'd change it to something like
```
AI_CV_FakeOut:
	if_type_effectiveness AI_EFFECTIVENESS_x0, Score_Minus10
	is_first_turn_for AI_USER, Score_Plus10
	goto Score_Minus10
```

**Comment by DizzyEggg** [comment]
Should it always use Fake Out on the first turn tho? If you can give me an example where it doesn't, and uses an objectively worse move, I'll try to think of something.

**Comment by segabl** [comment]
I mean it's a free turn, you can't go wrong with that

**Comment by DizzyEggg** [comment]
The mon could have Own Tempo, or it could be a double battle with some protection involved, idk

**Comment by DizzyEggg** [comment]
Alright, made Fake Out more likely to be used in singles, while keeping the same added score in doubles.

4a5a84e5c
