### ISSUE TITLE
Ice Body not healing at end of turn

### ISSUE THREAD

**Issue by segabl** [DizzyEggg/pokeemerald#235]
Pretty much what the title says. The Ice Body ability doesn't heal if the weather is hail. It didn't work for my Dewgong nor did it work for 2 npc mons that I gave the ability. It does however, protect from hail damage if the pokemon having it is not an ice type (observed with Gardevoir tracing Ice Body).

**Comment by DizzyEggg** [comment]
Forgot about brackets...

06a9165f7
