### ISSUE TITLE
Power Gem freezes the game

### ISSUE THREAD

**Issue by PALPATlNE** [DizzyEggg/pokeemerald#240]
Whenever a Pokémon uses Power Gem. It plays the animation, but stops after the blue orbs scatter. The Target glows with various colours and stops. Afterwards the screen is frozen, music still plays but you cannot do anything other than soft reset or close the emulator.

**Comment by segabl** [comment]
Doesn't happen for me. Which emulator are you using?

**Comment by PALPATlNE** [comment]
Oh yeah forgot to mention it is only in double battles. Have yet to test in singles.

I am usingg VBA

**Comment by DizzyEggg** [comment]
1d13004a0
