### ISSUE TITLE
Finish all abilities on battle_engine_v2

### ISSUE THREAD

**Issue by AsparagusEduardo** [DizzyEggg/pokeemerald#244]
This is a list with the current state of every ability of the battle_engine_v2.

******** GEN 4 ABILITIES *********
- [x] TANGLED_FEET
- [x] MOTOR_DRIVE
- [x] RIVALRY
- [x] STEADFAST
- [x] SNOW_CLOAK
- [x] GLUTTONY
- [x] ANGER_POINT
- [x] UNBURDEN
- [x] HEATPROOF
- [x] SIMPLE
- [x] DRY_SKIN
- [x] DOWNLOAD
- [x] IRON_FIST
- [x] POISON_HEAL
- [x] ADAPTABILITY
- [x] SKILL_LINK
- [x] HYDRATION
- [x] SOLAR_POWER
- [x] QUICK_FEET
- [x] NORMALIZE
- [x] SNIPER
- [x] MAGIC_GUARD
- [x] NO_GUARD
- [x] STALL
- [x] TECHNICIAN
- [x] LEAF_GUARD
- [x] KLUTZ
- [x] MOLD_BREAKER
- [x] SUPER_LUCK
- [x] AFTERMATH
- [x] ANTICIPATION
- [x] FOREWARN
- [x] UNAWARE
- [x] TINTED_LENS
- [x] FILTER
- [x] SLOW_START
- [x] SCRAPPY
- [x] STORM_DRAIN
- [x] ICE_BODY
- [x] SOLID_ROCK
- [x] SNOW_WARNING
- [x] HONEY_GATHER
- [x] FRISK
- [x] RECKLESS
- [ ] MULTITYPE
- [x] FLOWER_GIFT
- [x] BAD_DREAMS

******** GEN 5 ABILITIES *********
- [ ] PICKPOCKET
- [x] SHEER_FORCE
- [x] CONTRARY
- [x] UNNERVE
- [x] DEFIANT
- [x] DEFEATIST
- [x] CURSED_BODY
- [x] HEALER
- [x] FRIEND_GUARD
- [x] WEAK_ARMOR
- [x] HEAVY_METAL
- [x] LIGHT_METAL
- [x] MULTISCALE
- [x] TOXIC_BOOST
- [x] FLARE_BOOST
- [x] HARVEST
- [ ] TELEPATHY
- [x] MOODY
- [x] OVERCOAT
- [x] POISON_TOUCH
- [x] REGENERATOR
- [x] BIG_PECKS
- [x] SAND_RUSH
- [x] WONDER_SKIN
- [x] ANALYTIC
- [x] ILLUSION
- [x] IMPOSTER
- [x] INFILTRATOR
- [x] MUMMY
- [x] MOXIE
- [x] JUSTIFIED
- [x] RATTLED
- [x] MAGIC_BOUNCE
- [x] SAP_SIPPER
- [x] PRANKSTER
- [x] SAND_FORCE
- [x] IRON_BARBS
- [x] ZEN_MODE
- [x] VICTORY_STAR
- [x] TURBOBLAZE
- [x] TERAVOLT
******** GEN 6 ABILITIES *********
- [x] AROMA_VEIL
- [x] FLOWER_VEIL
- [x] CHEEK_POUCH
- [x] PROTEAN
- [x] FUR_COAT
- [ ] MAGICIAN
- [x] BULLETPROOF
- [x] COMPETITIVE
- [x] STRONG_JAW
- [x] REFRIGERATE
- [x] SWEET_VEIL
- [x] STANCE_CHANGE
- [x] GALE_WINGS
- [x] MEGA_LAUNCHER
- [x] GRASS_PELT
- [ ] SYMBIOSIS
- [x] TOUGH_CLAWS
- [x] PIXILATE
- [x] GOOEY
- [x] AERILATE
- [ ] PARENTAL_BOND
- [x] DARK_AURA
- [x] FAIRY_AURA
- [x] AURA_BREAK
- [ ] PRIMORDIAL_SEA
- [ ] DESOLATE_LAND
- [ ] DELTA_STREAM
******** GEN 7 ABILITIES *********
- [x] STAMINA
- [ ] WIMP_OUT
- [x] EMERGENCY_EXIT
- [x] WATER_COMPACTION
- [x] MERCILESS
- [x] SHIELDS_DOWN
- [x] STAKEOUT
- [x] WATER_BUBBLE
- [x] STEELWORKER
- [x] BERSERK
- [x] SLUSH_RUSH
- [x] LONG_REACH
- [x] LIQUID_VOICE
- [x] TRIAGE
- [x] GALVANIZE
- [x] SURGE_SURFER
- [x] SCHOOLING
- [x] DISGUISE
- [ ] BATTLE_BOND
- [x] POWER_CONSTRUCT
- [x] CORROSION
- [x] COMATOSE
- [x] QUEENLY_MAJESTY
- [x] INNARDS_OUT
- [x] DANCER
- [x] BATTERY
- [x] FLUFFY
- [x] DAZZLING
- [x] SOUL_HEART
- [x] TANGLING_HAIR
- [x] RECEIVER
- [x] POWER_OF_ALCHEMY
- [x] BEAST_BOOST
- [ ] RKS_SYSTEM
- [x] ELECTRIC_SURGE
- [x] PSYCHIC_SURGE
- [x] MISTY_SURGE
- [x] GRASSY_SURGE
- [x] FULL_METAL_BODY
- [x] SHADOW_SHIELD
- [x] PRISM_ARMOR
- [x] NEUROFORCE

**Comment by DizzyEggg** [comment]
Project moved to RHH
