### ISSUE TITLE
[battle_engine_v2] No Guard is not affecting OHKO Moves, even though it should

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#247]
Title.

As you can see in [this video](https://youtu.be/psdM7xYn_Lc?t=86), No Guard in Ultra Sun & Ultra Moon affects OHKO Moves allowing them to always land on the target despite their low accuracy.

However, right now, No Guard is not affecting them in the bev2.
https://streamable.com/wubzc

**Comment by DizzyEggg** [comment]
41f0c0acb
