### ISSUE TITLE
Charge beam animation causes lock up

### ISSUE THREAD

**Issue by segabl** [DizzyEggg/pokeemerald#249]
Occured in double battle. The animation will play and the shaking of the targeted mon will loop infinitely.

**Comment by LOuroboros** [comment]
Can confirm the lock up, but in my case it's my partner who gets stuck in a shaking loop, not the targeted Pokémon. It doesn't matter if I target the opponent on the left, or the right, it's always my partner who gets stuck in a shaking loop
![2020-02-02_08-50-06](https://user-images.githubusercontent.com/4485172/73607762-14d46c80-4599-11ea-9c00-f52738d17ad4.gif)

**Comment by Ryuhouji** [comment]
Can confirm it is double and multibattles.

**Comment by DizzyEggg** [comment]
#252
