### ISSUE TITLE
Magnet Pull shows wrong ability name

### ISSUE THREAD

**Issue by segabl** [DizzyEggg/pokeemerald#255]
When trying to switch out a Pokemon that is trapped by Magnet Pull, the message will show the trapped Pokemon's ability name instead of the trapping one.

**Comment by DizzyEggg** [comment]
Cannot replicate, could you give more details?

**Comment by segabl** [comment]
I was fighting a Magneton with magnet pull with my Scizor, trying to switch showed the message "Magneton's Technician prevents switching"

**Comment by DizzyEggg** [comment]
You were right! Fixed in 360665fac
