### ISSUE TITLE
[battle_engine_v2] Teleport causing the game to freeze during a trainerbattle if aiFlags are used

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#256]
Title.

To test this out, what I did was:
-Set Magnemite's only known move in its Level Up Learnset to Teleport at Lv1.
-Set a trainer's _(Youngster Allen in Route 102)_ first Pokémon to Magnemite, by default he has a Zigzagoon.
The repository has no other changes, and the latest commit used is 8889039

The result is that whenever you're about to choose a move on your first turn, the game will freeze.

If you set the `TRAINER_ALLEN`'s `aiFlags` in `src/data/trainers.h` to 0, Allen's Magnemite's Teleport will fail normally and the game won't freeze.

**Comment by DizzyEggg** [comment]
14bc2f65f hopefully
