### ISSUE TITLE
Stance Change/Transform troubles

### ISSUE THREAD

**Issue by AsparagusEduardo** [DizzyEggg/pokeemerald#257]
A non-Aegislash transformed Pokémon is able to trigger Stance Chance, making it trapped in the changed form after the battle ends.

![StanceChangeBug](https://user-images.githubusercontent.com/2904965/73798936-24b7a080-4793-11ea-8221-208f81542a14.gif)

**Comment by DizzyEggg** [comment]
Lmao, that should not happen. Didn't test it, but should work c9774f6e2

**Comment by AsparagusEduardo** [comment]
Yeah, that's pretty much the fix I did for Disguise ( #258 ). I didn't fix it myself then because in Bulbapedia they claim that transformed Aegislash into Aegislash can still do it:
![image](https://user-images.githubusercontent.com/2904965/74085565-d9361880-4a58-11ea-8d95-8410733a03ed.png)
https://bulbapedia.bulbagarden.net/wiki/Stance_Change_(Ability)

Should we just leave it like this, then?
