### ISSUE TITLE
Spark is special when it should be physical.

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#260]
> Type | Electric
> Physical
> PP 20 (max. 32)
> Power 65
> Accuracy 100%
> Makes contact
> Affected by Protect
> Not affected by Magic Coat
> Not affected by Snatch
> Affected by Mirror Move
> Not affected by King's Rock

From bulbapedia.
https://i.imgur.com/LMRnwT0.png

**Comment by DizzyEggg** [comment]
bd8d304
