### ISSUE TITLE
Partner AI tries to Roost at Full HP

### ISSUE THREAD

**Issue by ExoryxHana** [DizzyEggg/pokeemerald#277]
Context: Multi battle, the partner ai mon was a Pidgeotto, and it had full hp. His moves were Roost Heat wave, U-turn and Hurricane.
The other 2 partner AI's mons were a Wartortle and a Larvitar.

- U-turn was supereffective against one of the 2 enemy mons and in the partner ai's party there was another pokemon the partner AI could've switched to that was advantaged against the other enemy mon. (Enemies: Poochyena and Zubat, so the AI can U-turn the Poochyena supereffectively and then switch to Larvitar and Stone Edge the Zubat).
- Hurricane can one shot any of the 2 enemy mons, 100%.
- Heat wave could've AT LEAST dealt 60% max hp damage to both enemy mons.

The thing is it behaves without any logic, because sometimes it uses Hurricane, and thus one shots one of them.
Sometimes goes 200 IQ and does exactly what i said, so it U-turns the Poochyena supereffectively and then switches to Larvitar and Stone Edges the Zubat, which is perfect.
And sometimes uses Heat Wave and hits both mon for 60-70% of their HP.

I mean, the best thing it could do is the 2nd case, and sometimes it does it perfectly, but sometimes..yeah, just decides to Roost at full HP.

Why does the AI's behavior always change for no reason?

**Comment by DizzyEggg** [comment]
Doesn't happen in the latest builds
