### ISSUE TITLE
first send out pokémon don't have abilities

### ISSUE THREAD

**Issue by mertens2** [DizzyEggg/pokeemerald#278]
well... here's the thing, the abilities aren't loaded for the first send out pokémon in battle, like if one of my pokémon has drizzle, and is send out at first, the ability won't activate, and shows as "----" in the debug menu. this applies also to wild and trainer's pokémon, and in double battles, both pokémon first send out won't have their respective abilities...

**Comment by LOuroboros** [comment]
Can't confirm. I've a clean and up-to-date copy of the battle_engine_v2, I gave Drizzle to my Torchic and it seems to be working correctly.
![2020-02-18_18-00-38](https://user-images.githubusercontent.com/4485172/74777630-a66dfa80-5278-11ea-8755-1330ec1a11b5.gif)

**Comment by mertens2** [comment]
seems like something failed, like an hour after posting this, i did the merge again and the ability did shown. i guess i should have put it here?
