### ISSUE TITLE
Quick guard protects wrong side

### ISSUE THREAD

**Issue by segabl** [DizzyEggg/pokeemerald#279]
If the AI uses quick guard, it will be unable to use priority moves against the player.

**Comment by DizzyEggg** [comment]
Are you sure? I cannot replicate that, could you give more details?

**Comment by segabl** [comment]
I'll try to replicate it. All I remember was fighting a Swellow which kept using quick guard and quick attack (might also be a good idea to have a separate effect for quick guard etc since ai prioritizes it as if it was protect). the swellow would use quick guard in the first round and then try to attack with quick attack next which always failed because of quick guard.

**Comment by DizzyEggg** [comment]
Tried both single and double battles, but could not reproduce.
