### ISSUE TITLE
Pokeballs in item expansion are unsupported by save block.

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#285]
There are only 4 bits assigned to pokeball data in pokemon substruct 3, thus resulting in ball id's from 17+ showing incorrectly in the summary screen. Notably, Premier ball shows as Dusk ball.
This was captured with a Premier ball:
https://i.imgur.com/26BY04v.png

**Comment by DizzyEggg** [comment]
Fixed in #473
