### ISSUE TITLE
AI forgets to delete old pokemon data after killing it?

### ISSUE THREAD

**Issue by ExoryxHana** [DizzyEggg/pokeemerald#292]
Dunno how to explain it, it's like it literally forgets to delete old pokemon data after killing a mon 

Context:
Single battle, me vs AI, the enemy had a Kadabra, which was slower than my Mon1.

Turn 1: With my Mon1 I hit the Kadabra with a Physical move, then the Kadabra hits me supereffectively and oneshots my Mon1.

I send out Mon2.

Turn 2: With my Mon2, which is slower than the enemy Kadabra, I select to use a Special move against it. (Mon2 has no physical moves).

Kadabra, which, again, is faster than my Mon2, uses Counter, which, obviously, fails. Then my Special Move hits and kills the Kadabra.

..I guess Counter was the right choice if Mon1 was still alive and in battle? Also why would you try to counter while having less than half hp versus a pokemon that has a supereffective move against you?

**Comment by DizzyEggg** [comment]
Should make the Counter issue less likely to happen 5d412d37d
