### ISSUE TITLE
Tall grass palette broken in item_expansion

### ISSUE THREAD

**Issue by sjgriffiths** [DizzyEggg/pokeemerald#293]
A clean build of the item_expansion branch has a broken brownish colour on stepped-on tall grass

![pokeemerald-grass-colour](https://user-images.githubusercontent.com/13700330/75118038-6a6ad900-566e-11ea-875a-9a3100af095d.png)

**Comment by AsparagusEduardo** [comment]
It's also affecting the Pokémon Center screen glow
![huh](https://user-images.githubusercontent.com/2904965/75126836-85ebd900-569a-11ea-8460-e674671992be.gif)

**Comment by DizzyEggg** [comment]
#296
