### ISSUE TITLE
[battle_engine_v2] Explosion + Damp issues

### ISSUE THREAD

**Issue by AsparagusEduardo** [DizzyEggg/pokeemerald#294]
- When Damp activates, it shows the attacker's ability instead of the target's. (fixed by #295) 
![oh](https://user-images.githubusercontent.com/2904965/75127332-5094ba80-569d-11ea-8cb1-08f05dc221e0.gif)
- In a double battle, there's an infinite loop when Damp activates.
![oh2](https://user-images.githubusercontent.com/2904965/75127335-58545f00-569d-11ea-8f06-98f26dcfba2b.gif)

**Comment by DizzyEggg** [comment]
6daab7a5c
