### ISSUE TITLE
Mold Breaker doesn't fully bypass Sticky Hold

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#297]
Title.
Sticky Hold is an ability that forbids the attacker from stealing the item that you _(the defender)_ are holding, if you're holding one.
However, because Mold Breaker/Teravolt/Turboblaze is supposed to bypass various abilities _(Sticky Hold included)_, a Pokémon with Mold Breaker should be able to steal the item that an opponent with Sticky Hold is carrying, for example by using the move Knock Off.

What is happening in the bev2 however is that, while the string of text saying how the Pokémon with Mold Breaker stole the foe's item does show up, the action of taking their item never really happens.

Video: https://streamable.com/777k1

**Comment by ExoryxHana** [comment]
Knock off is not supposed to steal the item, it just removes it.

Gen3 effect:
![chrome_mmnPYqde2Z](https://user-images.githubusercontent.com/42327659/75428400-64b01480-5948-11ea-9346-132b2e0d7297.png)

Gen 5 effect:
![chrome_OoXh87mSir](https://user-images.githubusercontent.com/42327659/75428412-68dc3200-5948-11ea-98b2-1e692b2a63e0.png)

**Comment by LOuroboros** [comment]
Yeah, I think I fucked up. I don't know why, but I remembered Knock Off being able to steal the target's items.
My bad. Thanks for the correction @ExoryxHana.
