### ISSUE TITLE
Illusion bugs

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#298]
![illusion](https://user-images.githubusercontent.com/28769716/75592809-29e4e280-5ae8-11ea-915f-14c15d0cef02.gif)
Illusion has a few issues:
- If a Pokemon with Illusion is the second Pokemon sent out in a double battle, it won't be shown as disguised unless the party menu is opened.
- If a Pokemon with Illusion is switched out while Illusion is still active, any Pokemon that switches in to replace it will be permanently disguised.
- When the player's Pokemon has Illusion, the action select text should use the Pokemon's name rather than the disguise's name e.g. player sends out Zorua disguised as Lillipup, text should be "What will Zorua do?" but is currently "What will Lillipup do?"

**Comment by DizzyEggg** [comment]
Yeah, I need to completely refactor how Illusion works

**Comment by DizzyEggg** [comment]
3bdf675
