### ISSUE TITLE
Download shows the wrong ability and species names.

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#299]
When using a porygon2 with download, it said "Arena Trap raised Dugtrio's Attack!" Instead of what it should have said: "Download raised Porygon2's Attack!"

**Comment by LOuroboros** [comment]
Can't confirm. Things are working correctly on my up-to-date copy of the battle engine v2 with nothing else added to it.
![2020-02-29_17-51-27](https://user-images.githubusercontent.com/4485172/75614914-32efa700-5b1c-11ea-8f72-ba2f1640e041.gif)![2020-02-29_17-50-05](https://user-images.githubusercontent.com/4485172/75614916-3420d400-5b1c-11ea-8c90-f137602efee1.gif)

**Comment by Ryuhouji** [comment]
Yes, it was reported by someone who thought they were on the latest version, that's my bad for not checking further. Closing.

**Comment by Toby313** [comment]
When my Lopunny faced a Download Porygon2, the game said Lopunny's Technician raised its Attack. (It's only a visual bug.) So this bug does seem to exist, but it is only when the _opposing_ pokemon has Download.

**Comment by LOuroboros** [comment]
> 
> 
> So this bug does seem to exist, but it is only when the _opposing_ pokemon has Download.

I just checked it myself with an up-to-date copy of the battle_engine_v2, and I still can't confirm.
![2020-04-15_14-12-54](https://user-images.githubusercontent.com/4485172/79366935-61d2a880-7f23-11ea-8575-6d9fc467fa0e.gif)
