### ISSUE TITLE
repel branch: Line 26 should be removeitem now

### ISSUE THREAD

**Issue by lightgod87** [DizzyEggg/pokeemerald#303]
Good day,

The motive for this issue is regarding the repel branch that has the BW Repel commit for this feature, as it's outdated in regards of the code nowadays. 

In line 26, the line was:

    takeitem VAR_0x8004, 1

But this gave me an error when building the rom:

```
   tools/preproc/preproc.exe data/event_scripts.s charmap.txt | arm-none-eabi-cpp -I include | arm-none-eabi-as -mcpu=arm7tdmi --defsym MODERN=0 -o build/emerald/data/event_scripts.o
   data/scripts/repel.inc: Assembler messages:
   data/scripts/repel.inc:26: Error: bad instruction `takeitem 0x8004,1'
   make: *** [Makefile:294: build/emerald/data/event_scripts.o] Error 1
```

Thanks to GriffinR, he pointed out that it should now be like this:

    removeitem VAR_0x8004, 1

After that, the issue disappeared. Can you please update this part of the code, so people won't have problems with building?

Thank you.

**Comment by DizzyEggg** [comment]
Thanks for letting me know! Fixed in f5d8de11d
