### ISSUE TITLE
[battle_engine_v2] Healing Wish can kill the last Pokémon alive in the party, but it shouldn't.

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#308]
Title.

This is what happens if you use Healing Wish in the battle_engine_v2 and you don't have any other Pokémon in your party, or well, you have but they're fainted:
![2020-03-11_10-11-51](https://user-images.githubusercontent.com/4485172/76430321-f418e700-638e-11ea-96e9-bc8e08ec9cb2.gif)

And this is what happens under the same conditions in Pokémon Ultra Sun:
https://streamable.com/sievp

**Comment by DizzyEggg** [comment]
efe17d995
