### ISSUE TITLE
[pokemon_expansion] Mega Medicham lacks an actual sprite

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#310]
Title.
![explorer-2020-03-16_21-51-14](https://user-images.githubusercontent.com/4485172/76811502-81fe3300-67d0-11ea-8b8d-25f3b3a2819f.png)
https://github.com/DizzyEggg/pokeemerald/tree/pokemon_expansion/graphics/pokemon/mega_medicham

**Comment by LOuroboros** [comment]
Primal Groudon, Primal Kyogre and Mega Rayquaza are missing one too.
I'll try to find some and submit a PR to address this today.

**Comment by DizzyEggg** [comment]
#354
