### ISSUE TITLE
[battle_engine_v2] Payback has its Gen. 4 effect instead of its Gen. 5+ effect

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#311]
As much as I love anything Gen. 4 related, I know this branch is supposed to have move effects that comply with Gen. 7 standards, so I feel the need to bring up this issue.

According to **[Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Payback_(move)#Generation_V_onwards)** and **[Smogon](https://www.smogon.com/dex/bw/moves/payback/)**, Payback's power should not be doubled if the opponent switches out their Pokémon starting from Gen. 5, however, in the battle_engine_v2 Payback's power IS being doubled.

For a test case, I tried to imitate what I did when I found the issue with Teleport freezing the game _(#256)_.

1) I made Torchic learn Payback in its level up learnset.
2) I modified Route 102's Youngster Calvin's party to a Lv2 Magnemite and a Lv100 Blastoise
3) I modified Magnemite's level up learnset to Splash at Lv1 and nothing else.
4) I raised the value of EFFECT_PAYBACK's `basePower` in `src/battle_util.c` to an obscenely high value
5) I built a ROM and tested.

Video: https://streamable.com/bc3cy

As usual, the test was made in an up-to-date and clean copy of the battle_engine_v2 with no other changes on my behalf.

**Comment by DizzyEggg** [comment]
458809c5f
