### ISSUE TITLE
[battle_engine_v2] Assurance's power should be doubled if the opponent hurts themself in confusion

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#312]
Title.
Right now, the power of Assurance is not being affected by the opponent hurting themself by being confused.
![2020-03-18_13-21-33](https://user-images.githubusercontent.com/4485172/76983096-9ef34d00-691b-11ea-8206-76a104bd772f.gif)

Test case:
-Torchic with Confuse Ray and Assurance
-Lv100 Electrode in Route 101 with no other move than Splash
-`basePower` in `case EFFECT_ASSURANCE` at `src/battle_util.c` set to `basePower *= 2000;`

Result:
-Torchic uses Confuse Ray to confuse Electrode
-Electrode tries to use a move but hurts themself in confusion
-Torchic uses Assurance, but the move isn't doing as much damage as it should be.

**Comment by DizzyEggg** [comment]
#313
