### ISSUE TITLE
[battle_engine_v2] Bug Bite isn't actually making the user eat the stolen berry

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#315]
Title.
Bug Bite is a move that does damage. If the opponent is holding a berry, the user steals the berry and eats it on the spot effectively benefitting from said berry's effect.

In the battle_engine_v2 however, while there's a text string saying that the user stole and ate the berry, the user is not actually eating the berry.
![2020-03-20_18-37-44](https://user-images.githubusercontent.com/4485172/77208305-4f0eb480-6ada-11ea-8ead-4183c1657a60.gif)

Test case:
-Made Torchic learn Bug Bite at Lv10
-Changed all the encounters in Route 102 with Lv5 Poochyena
-Changed Poochyena's held items to `ITEM_ORAN_BERRY` in `src/data/pokemon/base_stats.h`
-Built a ROM and tested the move

As usual, besides those small changes the copy of the battle_engine_v2 that I'm using is clean and on its latest commit.

**Comment by DizzyEggg** [comment]
Moved to RHH
