### ISSUE TITLE
 [battle_engine_v2] Lunar Dance shouldn't have the exact same move effect as Healing Wish

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#316]
Title.
Right now, both moves use the same move effect in the battle_engine_v2, the thing is, they don't work exactly the same in the official games.

Lunar Dance restores the HP and status conditions of the Pokémon that is being sent just like Healing Wish does.
However, unlike Healing Wish, Lunar Dance also fixes the PPs of the moves of the Pokémon that is being sent out.

Here's a short video depicting them.
Lunar Dance: https://streamable.com/vsck9
Healing Wish: https://streamable.com/26zbm

Lunar Dance is healing up the PP of my Decidueye's Tackle, but Healing Wish is not.

**Comment by DizzyEggg** [comment]
They have the same effect, but that part is handled by the battlescript itself as seen there https://github.com/DizzyEggg/pokeemerald/blob/battle_engine_v2/data/battle_scripts_1.s#L1530
