### ISSUE TITLE
[pokemon_expansion] EVO_LEVEL_SPECIFIC_MON_TYPE_IN_PARTY isn't working correctly

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#317]
This was talked about some time ago in Discord and it was never brought up here, so I'm taking the chance now that I've been testing the new evolution methods for reasons.

Correct me if I'm wrong, but I think this evolution method doesn't really work?

In `src/pokemon.c`, this evolution method seems to expect 2 parameters at the same time, a level and a type, but you can't have them both unless you expand the amount of parameters of the evolutions table or something like that *(I suppose)*.

I quickly set up a branch with the battle_engine_v2 and the pokemon_expansion just now, and if I raise Pancham to Lv32 _([the only Pokémon that uses this evo method](https://github.com/DizzyEggg/pokeemerald/blob/887fb1b45c849705b34bfdcab182b63e624d7772/src/data/pokemon/evolution.h#L398))_, nothing really happens.
I'm guessing it's because feeding this particular evolution method 1 parameter is not enough.

**Comment by DizzyEggg** [comment]
#329
