### ISSUE TITLE
[item_expansion] Global icon for Fairy TMHM is missing

### ISSUE THREAD

**Issue by lightgod87** [DizzyEggg/pokeemerald#318]
Good day,

This issue is for reporting that the global icon palette for the Fairy TMHM is missing. There's Fairy Gem and Fairy Memory, but not Fairy TMHM, and it's required for the TMHM implementation to go alright, as TM99 in Gen VII is Dazzling Gleam, which is a fairy move.

![imagen](https://user-images.githubusercontent.com/28798472/77827924-8850b100-70e6-11ea-80ac-d3c180679236.png)

Just to keep in mind.

**Comment by ultima-soul** [comment]
To add on to this, Bug type is also missing

**Comment by DizzyEggg** [comment]
#327
