### ISSUE TITLE
Wild Double Battle Graphical Error

### ISSUE THREAD

**Issue by Kurausukun** [DizzyEggg/pokeemerald#32]
When using a move that targets both opponents in a wild double battle, the attack does damage to both opponents normally, but the graphics act as if only one Pokemon was targeted instead of going down the middle of both Pokemon like in a trainer battle; this issue is not present in trainer battles (I noticed this when using Bubblebeam if it matters).

EDIT: As huderlem mentions below, I misunderstood the issue. The issue is not that graphics in wild doubles are messed up, but that moves that have been changed to hit multiple opponents need to have their animations changed.

**Comment by huderlem** [comment]
The issue is definitely present in trainer battles for bubblebeam.  Any moves that have been changed to `MOVE_TARGET_BOTH` would need to have their anim code changed to make use of `SetAverageBattlerPositions` and an additional `AnimTask_ShakeMon`, or whatever is appropriate in each case.

**Comment by DizzyEggg** [comment]
Fixed for Bubblebeam in 62863516c and 83936185b. Please let me know if there are any other moves like Bubblebeam.
