### ISSUE TITLE
magic guard doesn't cover all its bases

### ISSUE THREAD

**Issue by BluRosie** [DizzyEggg/pokeemerald#320]
according to https://bulbapedia.bulbagarden.net/wiki/Magic_Guard_(Ability)
magic guard also covers weather damage, both entry hazard damage and things like wrap, recoil, life orb, crash damage (a la high jump kick), etc.
if you want, i can fix this in a pull request sometime later today
i don't have a means to test this from the games 100%, so sorry if i need to prove this or something

**Comment by LOuroboros** [comment]
I gave it a quick test and I can confirm that weather damage is definitely affecting my Torchic with Magic Guard in an up-to-date copy of the battle_engine_v2.
I checked things by giving Magic Guard to my Torchic and fighting against Tyranitar with Sand Stream and Dewgong with Snow Warning.
https://streamable.com/w0v4kn

**Comment by DizzyEggg** [comment]
51e163951
