### ISSUE TITLE
Levitate has no ability pop-up

### ISSUE THREAD

**Issue by Bidoofremix** [DizzyEggg/pokeemerald#321]
It seems that when Levitate activates, the ability pop-up does not appear. I tested this with Earthquake (please see video at: https://www.youtube.com/watch?v=rJV3ELS_bs4). I cloned the newest version of the repo on 12th April and confirmed that other abilities, such as Flash Fire, do activate the pop-up.

**Comment by DizzyEggg** [comment]
51e2e0ad1
