### ISSUE TITLE
Finish all move effects on battle_engine_v2

### ISSUE THREAD

**Issue by AsparagusEduardo** [DizzyEggg/pokeemerald#328]
******** GEN 4   MOVES *********
- [X] ROOST
- [X] GRAVITY
- [X] MIRACLE_EYE
- [X] WAKE_UP_SLAP
- [X] HAMMER_ARM
- [X] GYRO_BALL
- [X] HEALING_WISH
- [X] BRINE
- [X] NATURAL_GIFT
- [X] FEINT
- [X] PLUCK
- [X] TAILWIND
- [X] ACUPRESSURE
- [X] METAL_BURST
- [X] U_TURN
- [X] CLOSE_COMBAT
- [X] PAYBACK
- [X] ASSURANCE
- [X] EMBARGO
- [X] FLING
- [X] PSYCHO_SHIFT
- [X] TRUMP_CARD
- [X] HEAL_BLOCK
- [X] WRING_OUT
- [X] POWER_TRICK
- [X] GASTRO_ACID
- [X] LUCKY_CHANT
- [X] ME_FIRST
- [X] COPYCAT
- [X] POWER_SWAP
- [X] GUARD_SWAP
- [X] PUNISHMENT
- [X] LAST_RESORT
- [X] WORRY_SEED
- [X] SUCKER_PUNCH
- [X] TOXIC_SPIKES
- [X] HEART_SWAP
- [X] AQUA_RING
- [X] MAGNET_RISE
- [X] FLARE_BLITZ
- [X] FORCE_PALM
- [X] AURA_SPHERE
- [X] ROCK_POLISH
- [X] POISON_JAB
- [X] DARK_PULSE
- [X] NIGHT_SLASH
- [X] AQUA_TAIL
- [X] SEED_BOMB
- [X] AIR_SLASH
- [X] X_SCISSOR
- [X] BUG_BUZZ
- [X] DRAGON_PULSE
- [X] DRAGON_RUSH
- [X] POWER_GEM
- [X] DRAIN_PUNCH
- [X] VACUUM_WAVE
- [X] FOCUS_BLAST
- [X] ENERGY_BALL
- [X] BRAVE_BIRD
- [X] EARTH_POWER
- [X] SWITCHEROO
- [X] GIGA_IMPACT
- [X] NASTY_PLOT
- [X] BULLET_PUNCH
- [X] AVALANCHE
- [X] ICE_SHARD
- [X] SHADOW_CLAW
- [X] THUNDER_FANG
- [X] ICE_FANG
- [X] FIRE_FANG
- [X] SHADOW_SNEAK
- [X] MUD_BOMB
- [X] PSYCHO_CUT
- [X] ZEN_HEADBUTT
- [X] MIRROR_SHOT
- [X] FLASH_CANNON
- [X] ROCK_CLIMB
- [X] DEFOG
- [X] TRICK_ROOM
- [X] DRACO_METEOR
- [X] DISCHARGE
- [X] LAVA_PLUME
- [X] LEAF_STORM
- [X] POWER_WHIP
- [X] ROCK_WRECKER
- [X] CROSS_POISON
- [X] GUNK_SHOT
- [X] IRON_HEAD
- [X] MAGNET_BOMB
- [X] STONE_EDGE
- [X] CAPTIVATE
- [X] STEALTH_ROCK
- [X] GRASS_KNOT
- [X] CHATTER
- [ ] JUDGMENT - TODO: Plate type effect
- [X] BUG_BITE
- [X] CHARGE_BEAM
- [X] WOOD_HAMMER
- [X] AQUA_JET
- [X] ATTACK_ORDER
- [X] DEFEND_ORDER
- [X] HEAL_ORDER
- [X] HEAD_SMASH
- [X] DOUBLE_HIT
- [X] ROAR_OF_TIME
- [X] SPACIAL_REND
- [X] LUNAR_DANCE
- [X] CRUSH_GRIP
- [X] MAGMA_STORM
- [X] DARK_VOID
- [X] SEED_FLARE
- [X] OMINOUS_WIND
- [X] SHADOW_FORCE

******** GEN 5   MOVES *********
- [X] HONE_CLAWS
- [X] WIDE_GUARD
- [X] GUARD_SPLIT
- [X] POWER_SPLIT
- [X] WONDER_ROOM
- [X] PSYSHOCK
- [X] VENOSHOCK
- [X] AUTOTOMIZE
- [X] RAGE_POWDER
- [X] TELEKINESIS
- [X] MAGIC_ROOM
- [X] SMACK_DOWN
- [X] STORM_THROW
- [X] FLAME_BURST
- [X] SLUDGE_WAVE
- [X] QUIVER_DANCE
- [X] HEAVY_SLAM
- [X] SYNCHRONOISE
- [X] ELECTRO_BALL
- [X] SOAK
- [X] FLAME_CHARGE
- [X] COIL
- [X] LOW_SWEEP
- [X] ACID_SPRAY
- [X] FOUL_PLAY
- [X] SIMPLE_BEAM
- [X] ENTRAINMENT
- [X] AFTER_YOU
- [X] ROUND
- [X] ECHOED_VOICE
- [X] CHIP_AWAY
- [X] CLEAR_SMOG
- [X] STORED_POWER
- [X] QUICK_GUARD
- [x] ALLY_SWITCH
- [X] SCALD
- [X] SHELL_SMASH
- [X] HEAL_PULSE
- [X] HEX
- [ ] SKY_DROP
- [X] SHIFT_GEAR
- [X] CIRCLE_THROW
- [X] INCINERATE
- [X] QUASH
- [X] ACROBATICS
- [X] REFLECT_TYPE
- [X] RETALIATE
- [X] FINAL_GAMBIT
- [X] BESTOW
- [X] INFERNO
- [X] WATER_PLEDGE
- [X] FIRE_PLEDGE
- [X] GRASS_PLEDGE
- [X] VOLT_SWITCH
- [X] STRUGGLE_BUG
- [X] BULLDOZE
- [X] FROST_BREATH
- [X] DRAGON_TAIL
- [X] WORK_UP
- [X] ELECTROWEB
- [X] WILD_CHARGE
- [X] DRILL_RUN
- [X] DUAL_CHOP
- [X] HEART_STAMP
- [X] HORN_LEECH
- [X] SACRED_SWORD
- [X] RAZOR_SHELL
- [X] HEAT_CRASH
- [X] LEAF_TORNADO
- [X] STEAMROLLER
- [X] COTTON_GUARD
- [X] NIGHT_DAZE
- [X] PSYSTRIKE
- [X] TAIL_SLAP
- [X] HURRICANE
- [X] HEAD_CHARGE
- [X] GEAR_GRIND
- [X] SEARING_SHOT
- [X] TECHNO_BLAST
- [X] RELIC_SONG
- [X] SECRET_SWORD
- [X] GLACIATE
- [X] BOLT_STRIKE
- [X] BLUE_FLARE
- [X] FIERY_DANCE
- [X] FREEZE_SHOCK
- [X] ICE_BURN
- [X] SNARL
- [X] ICICLE_CRASH
- [X] V_CREATE
- [X] FUSION_FLARE
- [X] FUSION_BOLT

******** GEN 6   MOVES *********
- [X] FLYING_PRESS
- [X] MAT_BLOCK
- [X] BELCH
- [X] ROTOTILLER
- [X] STICKY_WEB
- [X] FELL_STINGER
- [X] PHANTOM_FORCE
- [X] TRICK_OR_TREAT
- [X] NOBLE_ROAR
- [X] ION_DELUGE
- [X] PARABOLIC_CHARGE
- [X] FOREST_S_CURSE
- [X] PETAL_BLIZZARD
- [X] FREEZE_DRY
- [X] DISARMING_VOICE
- [X] PARTING_SHOT
- [X] TOPSY_TURVY
- [X] DRAINING_KISS
- [X] CRAFTY_SHIELD
- [X] FLOWER_SHIELD
- [X] GRASSY_TERRAIN
- [X] MISTY_TERRAIN
- [X] ELECTRIFY
- [X] PLAY_ROUGH
- [X] FAIRY_WIND
- [X] MOONBLAST
- [X] BOOMBURST
- [x] FAIRY_LOCK
- [X] KING_S_SHIELD
- [X] PLAY_NICE
- [X] CONFIDE
- [X] DIAMOND_STORM
- [X] STEAM_ERUPTION
- [X] HYPERSPACE_HOLE
- [X] WATER_SHURIKEN
- [X] MYSTICAL_FIRE
- [X] SPIKY_SHIELD
- [X] AROMATIC_MIST
- [X] EERIE_IMPULSE
- [X] VENOM_DRENCH
- [X] POWDER
- [x] GEOMANCY
- [X] MAGNETIC_FLUX
- [X] HAPPY_HOUR
- [X] ELECTRIC_TERRAIN
- [X] DAZZLING_GLEAM
- [X] CELEBRATE
- [X] HOLD_HANDS
- [X] BABY_DOLL_EYES
- [X] NUZZLE
- [X] HOLD_BACK
- [X] INFESTATION
- [X] POWER_UP_PUNCH
- [X] OBLIVION_WING
- [X] THOUSAND_ARROWS
- [X] THOUSAND_WAVES
- [X] LAND_S_WRATH
- [X] LIGHT_OF_RUIN
- [X] ORIGIN_PULSE
- [X] PRECIPICE_BLADES
- [X] DRAGON_ASCENT
- [ ] HYPERSPACE_FURY

******** GEN 7   MOVES *********
- [x] SHORE_UP
- [X] FIRST_IMPRESSION
- [X] BANEFUL_BUNKER
- [X] SPIRIT_SHACKLE
- [X] DARKEST_LARIAT
- [X] SPARKLING_ARIA
- [X] ICE_HAMMER
- [X] FLORAL_HEALING
- [X] HIGH_HORSEPOWER
- [X] STRENGTH_SAP
- [X] SOLAR_BLADE
- [X] LEAFAGE
- [X] SPOTLIGHT
- [X] TOXIC_THREAD
- [X] LASER_FOCUS
- [X] GEAR_UP
- [X] THROAT_CHOP
- [X] POLLEN_PUFF
- [X] ANCHOR_SHOT
- [X] PSYCHIC_TERRAIN
- [X] LUNGE
- [X] FIRE_LASH
- [X] POWER_TRIP
- [x] BURN_UP
- [X] SPEED_SWAP
- [X] SMART_STRIKE
- [x] PURIFY
- [X] REVELATION_DANCE
- [X] CORE_ENFORCER
- [X] TROP_KICK
- [X] INSTRUCT
- [ ] BEAK_BLAST
- [X] CLANGING_SCALES
- [X] DRAGON_HAMMER
- [X] BRUTAL_SWING
- [X] AURORA_VEIL
- [X] SHELL_TRAP
- [X] FLEUR_CANNON
- [X] PSYCHIC_FANGS
- [X] STOMPING_TANTRUM
- [X] SHADOW_BONE
- [X] ACCELEROCK
- [X] LIQUIDATION
- [X] PRISMATIC_LASER
- [X] SPECTRAL_THIEF
- [X] SUNSTEEL_STRIKE
- [X] MOONGEIST_BEAM
- [X] TEARFUL_LOOK
- [X] ZING_ZAP
- [X] NATURES_MADNESS
- [ ] MULTI_ATTACK
- [X] MIND_BLOWN
- [ ] PLASMA_FISTS
- [ ] PHOTON_GEYSER
- [X] DOUBLE_IRON_BASH

**Comment by LOuroboros** [comment]
Since Melmetal is a part of the pokemon_expansion, I think Double Iron Bash should also be taken into account.

**Comment by DizzyEggg** [comment]
Moved to RHH
