### ISSUE TITLE
Psycho Cut's animation is buggy

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#333]
It seems the background effect (which dims the battle background and some of the Pokemon on the field) isn't cleared after the animation finishes, which causes some visual bugs:

![pokeemerald-1](https://user-images.githubusercontent.com/28769716/79633077-497abc00-81b7-11ea-9645-e662ae02b6b8.png)
![pokeemerald-2](https://user-images.githubusercontent.com/28769716/79633078-4a135280-81b7-11ea-9b08-af003451e1af.png)
![pokeemerald-0](https://user-images.githubusercontent.com/28769716/79633074-48e22580-81b7-11ea-9124-26ddf8d32e0b.png)

**Comment by DizzyEggg** [comment]
bc86292c9
