### ISSUE TITLE
Traded Pokemon show the ability popup box when loafing around

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#334]
Scenario: If a traded Pokemon disobeys orders by loafing around for a turn, the ability popup box appears with garbage data in it, along with the "loafing around" string.

Expected behavior: the ability pop up box should appear if a Pokemon is loafing around due to Truant, but not if it's disobeying the player.

**Comment by DizzyEggg** [comment]
1395a7d38
