### ISSUE TITLE
HP berries should be eaten immediately after taking damage

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#336]
In gen 3 berries that activate once HP drops below a certain percentage (e.g Sitrus, Petaya) are eaten at the end of the turn. In later gens these are eaten straight away.

E.g. Pokemon A uses Rock Blast on Pokemon B (which has a Sitrus berry), it hits 5 times. The third hit drops its HP to 50%, and Pokemon B eats the Sitrus berry before the next two hits happen.

**Comment by DizzyEggg** [comment]
5ddb463
