### ISSUE TITLE
AI doesn't know grass types are immune to powder moves

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#343]
Had a trainer's Paras use Stun Spore on my Shroomish over and over, despite it being immune to it.

There might also be a similar issue with Overcoat and Safety Goggles; I couldn't find a check for them, but didn't test.

**Comment by ExoryxHana** [comment]
Was it a single battle or a double battle?
Did the trainer have those flags on? VIABILITY, CHECK_BAD_MOVES, TRY_TO_FAINT

**Comment by BuffelSaft** [comment]
It was a single battle, trainer flags were AI_SCRIPT_CHECK_BAD_MOVE, AI_SCRIPT_TRY_TO_FAINT, AI_SCRIPT_CHECK_VIABILITY.

**Comment by DizzyEggg** [comment]
28805b0f9
