### ISSUE TITLE
Poison Point doesn't do anything. Just shows activation message.

### ISSUE THREAD

**Issue by ExoryxHana** [DizzyEggg/pokeemerald#345]
https://cdn.discordapp.com/attachments/597726734900789250/701901508525949099/1YrMvIdOV0.mp4

**Comment by LOuroboros** [comment]
Can't confirm. Poison Point is working just fine on my end in individual wild battles and double ones too, in an up-to-date copy of the battle_engine_v2.
![2020-04-20_18-20-59](https://user-images.githubusercontent.com/4485172/79801372-65579c80-8334-11ea-9a2a-07eeb6b3f4af.gif)
![2020-04-20_18-23-48](https://user-images.githubusercontent.com/4485172/79801376-6688c980-8334-11ea-8341-1d796f76e9d8.gif)

**Comment by DizzyEggg** [comment]
As Lunos said, cannot reproduce
