### ISSUE TITLE
Finish all item hold effects on battle_engine_v2

### ISSUE THREAD

**Issue by AsparagusEduardo** [DizzyEggg/pokeemerald#351]
******** GEN 4 ITEMS*********
- [X] CHOICE_SCARF
- [X] CHOICE_SPECS
- [X] DAMP_ROCK
- [X] GRIP_CLAW
- [X] HEAT_ROCK
- [X] ICY_ROCK
- [X] LIGHT_CLAY
- [X] SMOOTH_ROCK
- [x] POWER_HERB
- [X] BIG_ROOT
- [X] EXPERT_BELT
- [X] LIFE_ORB
- [x] METRONOME
- [X] MUSCLE_BAND
- [X] WIDE_LENS
- [X] WISE_GLASSES
- [X] ZOOM_LENS
- [X] LAGGING_TAIL
- [X] FOCUS_SASH
- [X] FLAME_ORB
- [X] TOXIC_ORB
- [X] STICKY_BARB
- [X] IRON_BALL
- [X] BLACK_SLUDGE
- [x] DESTINY_KNOT
- [x] SHED_SHELL
- [X] QUICK_POWDER
- [X] ADAMANT_ORB
- [X] LUSTROUS_ORB
- [X] GRISEOUS_ORB
- [ ] GRACIDEA
- [X] RESIST_BERRY
- [ ] EV_BOOST - Slows down, but no EV   gain
 
******** GEN 5 ITEMS*********
- [X] FLOAT_STONE
- [X] EVIOLITE
- [X] ASSAULT_VEST
- [X] DRIVE
- [X] GEMS
- [X] ROCKY_HELMET
- [X] AIR_BALLOON
- [ ] RED_CARD
- [X] RING_TARGET
- [X] BINDING_BAND
- [ ] EJECT_BUTTON
- [X] ABSORB_BULB
- [X] CELL_BATTERY
 
******** GEN 6 ITEMS*********
- [X] FAIRY_POWER
- [X] MEGA_STONE
- [X] SAFETY_GOOGLES
- [X] LUMINOUS_MOSS
- [X] SNOWBALL
- [X] WEAKNESS_POLICY
 
******** GEN 7 ITEMS*********
- [X] PROTECTIVE_PADS
- [X] TERRAIN_EXTENDER
- [ ] SEEDS
- [x] ADRENALINE_ORB
- [X] MEMORY

**Comment by DizzyEggg** [comment]
Moved to RHH
