### ISSUE TITLE
Base power of Acrobatics should be calculated after consuming a flying gem

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#358]
Currently Acrobatics behaves as if the user is still holding an item when it's boosted by a flying gem. 

Test scenario:
- Enemy trainer's Fletchinder had a flying gem, used Acrobatics on my Gastrodon, got a critical hit
- Gastrodon lost about 35% of its HP, which is what was expected from a move with 55 base power

Image here shows Gastrodon's HP after being hit, if anyone wants to double check the damage. Gastrodon has 57 defense, and Fletchinder has 53 attack.
![pokeemerald-0](https://user-images.githubusercontent.com/28769716/80346201-779a8300-88be-11ea-86de-49808d1f1a34.png)

Expected behavior:
- Pokemon uses Acrobatics
- Flying gem is consumed, boosting the move's power
- Pokemon now has no held item, so Acrobatics' base power should be doubled as well

**Comment by DizzyEggg** [comment]
432ae465700154dee811f9a04a0c8b79a8803c92
