### ISSUE TITLE
Gems are consumed on the wrong attack

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#365]
![Grass Gem](https://user-images.githubusercontent.com/28769716/80580334-7eacc700-8a5f-11ea-84eb-583a141ab012.gif)
Gems are always used up on the holder's first attack, even if the attack is the wrong type. Don't know if they're also boosting damage, but they're definitely consumed afterwards.

**Comment by DizzyEggg** [comment]
f71f1c9
