### ISSUE TITLE
Tailwind shows wrong string when used by an opponent

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#366]
![Tailwind](https://user-images.githubusercontent.com/28769716/80581299-12cb5e00-8a61-11ea-8fb9-84fb28356258.gif)

Very minor issue: string should say "The Tailwind blew from behind the opposing team!" here instead of "The Tailwind blew from behind your team!"

**Comment by DizzyEggg** [comment]
a848c9679
