### ISSUE TITLE
[battle_engine_v2]: AI should check for immunity due to Storm Drain

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#372]
The AI currently behaves like it does in gen 5+ (i.e. it doesn't know the ability exists, and will just use water attacks on a Gastrodon over and over).

Very easy to fix by adding a check for it to AI_CBM_CheckIfNegatesType. Would you prefer a pull request or an issue report for little things like this?

**Comment by DizzyEggg** [comment]
cfc1ea7db
