### ISSUE TITLE
Vacuum Wave animation bugged in double battles

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#375]
Similar to dragon pulse and many other animations previously, Vacuum Wave animation is bugged in double battles. Are you guys even testing double battles when you add new anims?

**Comment by LOuroboros** [comment]
Can confirm.
![2020-05-12_20-06-23](https://user-images.githubusercontent.com/4485172/81754315-44461f80-948c-11ea-8701-ff13fe85b72c.gif)

**Comment by DizzyEggg** [comment]
f5b55ddff
