### ISSUE TITLE
Repeated use of acupressure causes the game to lifelock

### ISSUE THREAD

**Issue by SBird1337** [DizzyEggg/pokeemerald#380]
Using the move `Acupressure` repeatedly (Might need several pp magazines of it for the bug to trigger) causes the game to enter some sort of lifelock (Interrupts are still active, music still plays, but logic does not work anymore, and you cannot do any input)

**Steps to reproduce**
 1. Enter a battle
 2. Spam acupressure
 3. The game hangs

**Expected behavior**
The game does not hang

**Related issues**
pokemon-sots/pokemon-sots-issues#133

**Possible culprit**
In the `various` variant for `tryacupressure` there is these lines of code:
```C
do
{
    statId = (Random() % NUM_BATTLE_STATS) + 1;
} while (!(bits & gBitTable[statId]));
```

I think this may cause statId to take the value of a non-existant stat, which might be related, I'm not really sure this is really the case.

**Comment by DizzyEggg** [comment]
#381
