### ISSUE TITLE
Mon's sprite stays after using Teleport in a wild double battle

### ISSUE THREAD

**Issue by Fontbane** [DizzyEggg/pokeemerald#386]
If you have let's say an Abra and it uses Teleport in a wild double battle, its sprite will stay on the screen until you refresh it by going to the bag or mon selection screen, or if the battle ends. This is purely a graphical error.
![Screenshot_560](https://user-images.githubusercontent.com/36677462/82732450-3f2e6f00-9cdb-11ea-934a-527f30e8a138.png)

**Comment by DizzyEggg** [comment]
fcc5ec1dd
