### ISSUE TITLE
The animation of Eerie Impulse crashes the game

### ISSUE THREAD

**Issue by Toby313** [DizzyEggg/pokeemerald#403]

**Comment by LOuroboros** [comment]
Can confirm. I think the problem is caused by the 12 `gZapCannonSparkSpriteTemplate` actions/commands.
Coincidentally, Electrify which is another move that makes use of it crashes the game as well.

**Comment by Ryuhouji** [comment]
_Do you guys not test these before implementing them? This happens far too often..._

**Comment by shinny456** [comment]
ight
