### ISSUE TITLE
[battle_engine_v2] Ember has weird graphics

### ISSUE THREAD

**Issue by Bidoofremix** [DizzyEggg/pokeemerald#408]
Hi, I've encountered an issue with Ember's graphics on the battle_engine_v2 branch. I have built pret/master and DizzyEggg/master to confirm that the graphics of the move look normal in those builds. Here is the code I used on battle_engine_v2 to produce the issue:

```
git clone https://github.com/pret/agbcc
git clone https://github.com/DizzyEggg/pokeemerald
cd pokeemerald
git checkout battle_engine_v2
cd ../agbcc
./build.sh
./install.sh ../pokeemerald
cd ../pokeemerald
make
```

I tested all three builds (pret/master, DizzyEggg/master and DizzyEggg/battle_engine_v2) on the same emulator. To see how the move looks like on battle_engine_v2, please see this video: https://www.youtube.com/watch?v=jKYkeKFKMgI

I am aware that this may be due to my environment (Win10, WSL, Ubuntu), but I couldn't figure out how pret/master and DizzyEggg/master would not be affected were this the case. Anyway, I thought this is weird enough to report.

**Comment by LOuroboros** [comment]
Various move animation particles have been modified by the PR #390.
You can disable them by changing the values in `include/constants/battle_config.h` from `TRUE` to FALSE` as you see fit.

**Comment by Bidoofremix** [comment]
Thank you for your quick reply. I will close this issue.
