### ISSUE TITLE
The animation of Revelation Dance softresets the game

### ISSUE THREAD

**Issue by Toby313** [DizzyEggg/pokeemerald#414]

**Comment by Toby313** [comment]
Should I put animation issues in one 'issue' or seperate? They keep coming.

**Comment by LOuroboros** [comment]
Normally, it's good practice to report every issue separately/individually.

**Comment by Toby313** [comment]
I'll go to town then

**Comment by LOuroboros** [comment]
I pinpointed the exact lines causing the crash. I'm gonna look into it.
![notepad++-2020-06-15_23-54-39](https://user-images.githubusercontent.com/4485172/84726618-ac909100-af63-11ea-9f0a-6ab948295b89.png)
