### ISSUE TITLE
Some to-do's (and Protean)

### ISSUE THREAD

**Issue by Squeetz** [DizzyEggg/pokeemerald#42]
Powder:
Add a case for CANCELLER_POWDER right before CANCELLER_THAW
effect = 0 to continue the loop in case the user is frozen and a move will thaw it first before executing Powder's damage battle script.
Do not clear Powdered status after checking as it lasts for the duration of the turn!

Protean:
See Discord DMs ;^)
Also note that Psychic Terrain's priority blocking effect needs to be checked in ABE's ABILITYEFFECT_MOVES_BLOCK and not in AtkCanceller_UnableToUseMove to make sure the Protean user gets to transform.

Heal Block:
Add EFFECT_DREAM_EATER in IsHealBlockPreventingMove and fix the message that shows the inability to use a heal blocked move.

**Comment by DizzyEggg** [comment]
Powder, Protean, Heal Block, Dazzling and Psychic Terrain are done.
