### ISSUE TITLE
The animation of Night Daze softresets the game

### ISSUE THREAD

**Issue by Toby313** [DizzyEggg/pokeemerald#424]
I'm starting to feel bad for this big wall of issues, but it had to be done. Also, sorry if some of these animation bugs are caused by the same thing making some of them redundant.

**Comment by MandL27** [comment]
Haven't checked the anim script myself, but I know Nasty Plot SRed because there was a duplicate `return` in the script. Maybe it's that bug again?

**Comment by Toby313** [comment]
I'm like a total noob at scripts so I'm just reporting what I see in-game
