### ISSUE TITLE
gEnemyParty gets corrupted by EWRAM access

### ISSUE THREAD

**Issue by ExpoSeed** [DizzyEggg/pokeemerald#427]
GriffinR: "Adding `EWRAM_DATA u8 gFiller[0x384] = {0};` anywhere before `gPlayerParty` in ram pushes `gPlayerParty` into the region of vanilla `gBattleBufferB` (and will specifically corrupt the second slot, same issue as before). In Egg's battle engine by default this region normally falls in `gEnemyParty`, which is why it wasnt an issue before. Adding the new string vars was enough to push it down"

**Comment by DizzyEggg** [comment]
This was caused by mega indicator sprite trying to adjust its x/y position based on the healthbox it was placed in, while the sprite was simply not there. It resulted in overwriting some random ram space.

f19ba68cb
