### ISSUE TITLE
Flame Burst doesn't damage both sides of the enemy team properly. 

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#444]
Using it on the right side enemy pokemon works correctly, using it on the left side pokemon does not.
https://cdn.discordapp.com/attachments/604524390314409984/724372955299053568/glitch.mp4

**Comment by DizzyEggg** [comment]
Cannot reproduce, please provide more info

**Comment by LOuroboros** [comment]
Can't confirm on my up-to-date copy of the battle_engine_v2
![2020-06-23_03-28-44](https://user-images.githubusercontent.com/4485172/85368510-c0a73600-b501-11ea-9289-346750475498.gif)
