### ISSUE TITLE
Heal Block doesn't fully prevent hp gain

### ISSUE THREAD

**Issue by Ryuhouji** [DizzyEggg/pokeemerald#445]
Specifically with Leech Seed, the target still regained hp even with heal block on them.

Quote:
"
problem with Heal Block, my Ivysaur used Leech seed , the enemy Elgyem used Heal Block, but I still recovered HP from leech seed. Bulbapedia says enemy pokemon will take damage from leech seed and yours wont recover HP, but I did get some hp back
"
from one of my players.

**Comment by DizzyEggg** [comment]
8998e54ce
