### ISSUE TITLE
Finish Pokémon Forms.

### ISSUE THREAD

**Issue by AsparagusEduardo** [DizzyEggg/pokeemerald#447]
**Introduced in Gen 4**
- [ ] Separate Deoxys forms
- [ ] Burmy/Wormadam
  - [x] Sand Cloak
  - [x] Trash Cloak
  - [ ] Switching forms after a battle.
- [ ] Shellos/Gastrodon
  - [x] West Sea (folder is called "gastrodonE")
  - [ ] East Sea
- [x] Rotom
  - [x] Normal
  - [x] Heat
  - [x] Wash
  - [x] Frost
  - [x] Fan
  - [x] Mow
- [ ] Giratina
  - [x] Altered
  - [x] Origin
  - [ ] Change form while holding Grisous Orb.
- [ ] Shaymin
  - [x] Land
  - [x] Sky
    - [ ] Level up learnset.
  - [ ] Using Gracidea outside of battle to change form.
  - [ ] Go back when night/frozen.
- [ ] Arceus
  - [ ] Change form while holding plates.

**Introduced in Gen 5**
- [ ] Basculin
  - [x] Red-striped
  - [ ] Blue-striped
- [x] Darmanitan 
  - [x] Zen Mode
  - [x] In-battle effect.
- [ ] Deerling/Sawsbuck
  - [x] Spring
  - [ ] Summer
  - [ ] Autumn
  - [ ] Winter
- [ ] Tornadus/Thundurus/Landorus
  - [x] Incarnate
  - [x] Therian
  - [ ] Using Reveal Glass outside of battle to change form.
- [x] Kyurem
  - [x] White
  - [x] Black
  - [ ] Using Reveal Glass outside of battle to change form.
- [ ] Keldeo
  - [x] Ordinary
  - [ ] Resolute
- [ ] Meloetta
  - [x] Aria
  - [x] Pirouette
  - [ ] Relic Song form switch.
- [ ] Genesect
  - [x] No drive
  - [ ] Drives
  - [ ] Change form while holding drives.

**Introduced in Gen 6**
- [ ] Vivillon
  - [ ] Archipelago
  - [ ] Continental
  - [ ] Elegant
  - [ ] Garden
  - [ ] High Plains
  - [ ] Icy Snow
  - [ ] Jungle
  - [ ] Marine
  - [x] Meadow
  - [ ] Modern
  - [ ] Monsoon
  - [ ] Ocean
  - [ ] Polar
  - [ ] River
  - [ ] Sandstorm
  - [ ] Savanna
  - [ ] Sun
  - [ ] Tundra
  - [ ] Poké Ball
  - [ ] Fancy
- [ ] Flabébé/Floette/Florges
  - [x] Red
  - [ ] Yellow
  - [ ] Orange
  - [ ] Blue
  - [ ] White
- [ ] Furfrou
  - [x] Natural
  - [ ] Heart Trim
  - [ ] Star Trim
  - [ ] Diamond Trim
  - [ ] Debutante Trim
  - [ ] Matron Trim
  - [ ] Dandy Trim
  - [ ] La Reine Trim
  - [ ] Kabuki Trim
  - [ ] Pharaoh Trim
- [x] Aegislash
  - [x] Shield
  - [x] Blade
  - [x] Stance Change
- [ ] Pumpkaboo/Gourgeist
  - [ ] Small
  - [x] Average
  - [ ] Large
  - [ ] Super
- [ ] Xerneas
  - [ ] Neutral
  - [x] Active
- [ ] Primal Reversion
  - [x] Kyogre
  - [x] Groudon
  - [ ]  In battle effect
- [ ] Hoopa
  - [x] Confined
  - [x] Unbound
  - [ ] Using Prison Bottle outside of battle to change form.

**Introduced in SM**
- [ ] Cap Pikachu
  - [ ] Original
  - [ ] Hoenn
  - [ ] Sinnoh
  - [ ] Unova
  - [ ] Kalos
  - [ ] Alola
  - [ ] Partner
- [ ] Greninja
  - [x] Normal
  - [ ] Ash-Greninja
  - [ ] Battle Bond
- [ ] Zygarde
  - [x] 10%
  - [x] 50%
  - [x] Complete
  - [x] Power Construct switches forms
  - [ ] Zygarde Cube Switches Power Construct Zygarde between 10% & 50% out of battle.
- [ ] Oricorio
  - [x] Baile Style
  - [ ] Pom-Pom Style
  - [ ] Pa'u Style
  - [ ] Sensu Style
- [x] Lycanroc
  - [x] Midday
  - [x] Midnight
  - [x] Dusk
- [x] Whishiwashi
  - [x] Solo
  - [x] Schooling (form)
  - [x] Schooling (ability)
- [ ] Silvally
- [ ] Minior
  - [x] Meteor
  - [x] Core
  - [ ] Core Colors
  - [x] Shields Down
- [x] Mimikyu
  - [x] Disguised
  - [x] Busted
  - [x] Disguise (Ability)
- [x] Necrozma
  - [x] Normal
  - [ ] Dusk Mane
  - [ ] Dawn Wings
  - [ ] Ultra
- [ ] Magearna
  - [x] Normal
  - [ ] Original Color

**Gender differences**
  - [ ] Venusaur
  - [ ] Butterfree
  - [ ] Rattata
  - [ ] Raticate
  - [ ] Pikachu
  - [ ] Raichu
  - [ ] Zubat
  - [ ] Gloom
  - [ ] Vileplume
  - [ ] Kadabra
  - [ ] Alakazam
  - [ ] Doduo
  - [ ] Dodrio
  - [ ] Hypno
  - [ ] Rhyhorn
  - [ ] Rhydon
  - [ ] Goldeen
  - [ ] Seaking
  - [ ] Scyther
  - [ ] Magikarp
  - [ ] Gyarados
  - [ ] Eevee
  - [ ] Meganium
  - [ ] Ledyba
  - [ ] Ledian
  - [ ] Xatu
  - [ ] Sudowoodo
  - [ ] Politoed
  - [ ] Aipom
  - [ ] Wooper
  - [ ] Quagsire
  - [ ] Murkrow
  - [ ] Wobbuffet
  - [ ] Girafarig
  - [ ] Gligar
  - [ ] Steelix
  - [ ] Scizor
  - [ ] Heracross
  - [ ] Sneasel
  - [ ] Ursaring
  - [ ] Piloswine
  - [ ] Octillery
  - [ ] Houndoom
  - [ ] Donphan
  - [ ] Torchic
  - [ ] Combusken
  - [ ] Blaziken
  - [ ] Beautifly
  - [ ] Dustox
  - [ ] Ludicolo
  - [ ] Nuzleaf
  - [ ] Shiftry
  - [ ] Meditite
  - [ ] Medicham
  - [ ] Roselia
  - [ ] Gulpin
  - [ ] Swalot
  - [ ] Numel
  - [ ] Camerupt
  - [ ] Cacturne
  - [ ] Milotic
  - [ ] Relicanth
  - [ ] Starly
  - [ ] Staravia
  - [ ] Staraptor
  - [ ] Bidoof
  - [ ] Bibarel
  - [ ] Kricketot
  - [ ] Kricketune
  - [ ] Shinx
  - [ ] Luxio
  - [ ] Luxray
  - [ ] Roserade
  - [ ] Combee
  - [ ] Pachirisu
  - [ ] Buizel
  - [ ] Floatzel
  - [ ] Ambipom
  - [ ] Gible
  - [ ] Gabite
  - [ ] Garchomp
  - [ ] Hippopotas
  - [ ] Hippowdon
  - [ ] Croagunk
  - [ ] Toxicroak
  - [ ] Finneon
  - [ ] Lumineon
  - [ ] Snover
  - [ ] Abomasnow
  - [ ] Weavile
  - [ ] Rhyperior
  - [ ] Tangrowth
  - [ ] Mamoswine
  - [ ] Unfezant
  - [ ] Frillish
  - [ ] Jellicent
  - [ ] Pyroar
  - [x] Meowstick

**Comment by DizzyEggg** [comment]
Moved to RHH
