### ISSUE TITLE
Transform and Imposter do not fail against Illusion.

### ISSUE THREAD

**Issue by Toby313** [DizzyEggg/pokeemerald#448]
![pokeemerald_1593096988212](https://user-images.githubusercontent.com/56541253/85744082-e4869980-b704-11ea-9865-cf35e7487e21.png)
Here's a picture of Illusion Zorua being disguised as Magearna, yet Ditto still Transformed into Zorua.

**Comment by DizzyEggg** [comment]
36aec56
