### ISSUE TITLE
Surf Softlock Issue

### ISSUE THREAD

**Issue by Kurausukun** [DizzyEggg/pokeemerald#45]
When using Surf against an opposing team of Seaking and Tentacruel, after the first "It's not very effective" message appears, the text disappears and the game is softlocked. I haven't tested other similar situations to this, so I'm not sure exactly what triggers it.

**Comment by DizzyEggg** [comment]
Possibly fixed?

**Comment by DizzyEggg** [comment]
Fixed with Assists's fix.
