### ISSUE TITLE
The animations of moves with MOVE_TARGET_FOES_AND_ALLY only hit the partner in doubles when used by your pokemon on the right, even though they damage all pokemon.

### ISSUE THREAD

**Issue by Toby313** [DizzyEggg/pokeemerald#451]

**Comment by Toby313** [comment]
I just noticed this is only the case when used by the right pokemon, having the left pokemon use it seems to work fine.

**Comment by Toby313** [comment]
This might be the case for all/most moves that target all pokemon.

**Comment by DizzyEggg** [comment]
3cf091d63
