### ISSUE TITLE
U-Turn and Volt Switch don't fail (to switch) in the Battle Arena, leading to the user sending out a decamark after their 3rd pokemon.

### ISSUE THREAD

**Issue by Toby313** [DizzyEggg/pokeemerald#453]
![pokeemerald_1593212768039](https://user-images.githubusercontent.com/56541253/85907692-9f508d80-b812-11ea-95a7-342d999e1aa7.png)
![pokeemerald_1593212770699](https://user-images.githubusercontent.com/56541253/85907694-9fe92400-b812-11ea-807b-89e9d443b942.png)

**Comment by LOuroboros** [comment]
Can confirm.
https://streamable.com/a3fy3q

**Comment by DizzyEggg** [comment]
b1d0bc1 c93ab64
