### ISSUE TITLE
Mold Breaker users still get their attacks redirect by Move-drawing abilities.

### ISSUE THREAD

**Issue by Toby313** [DizzyEggg/pokeemerald#458]
Although the move gets redirected, the move doesn't get absorbed thanks to Mold Breaker.

**Comment by DizzyEggg** [comment]
could you be more specific with the moves and abilities?

**Comment by Toby313** [comment]
Lightning Rod/Storm Drain

**Comment by DizzyEggg** [comment]
52c63cd
