### ISSUE TITLE
Certain held berries revive fainted Pokemon

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#459]
If a Pokemon is KO'ed before eating its HP restoring berry, it eats the berry after fainting and regains HP, which revives it:
![Zombie](https://user-images.githubusercontent.com/28769716/86589796-71253780-bfe2-11ea-9388-f221b12744e8.gif)

**Comment by DizzyEggg** [comment]
sorry it took that long to fix fc510a6

**Comment by BuffelSaft** [comment]
A few days is a pretty quick fix, can't complain!
