### ISSUE TITLE
various move adjustments per bulbapedia.bulbagarden.net/wiki/List_of_modified_moves and Serebii's "updated moves" pages

### ISSUE THREAD

**Issue by amiosi** [DizzyEggg/pokeemerald#486]
This list is by no means comprehensive, these are just some things i noticed while working with this project.
---------------------------
swords dance pp 30 -> 20
whirlwind should be affected by magic coat
wrap accuracy 85 -> 90
teleport priority 0 -> -6 (gen 8 change)
smog power 20 -> 30
smog pp 30 -> 20 (both this and the above are human error)
poison gas should target both enemies
struggle should NOT be affected by mirror move
cotton spore should target both enemies
protect priority 3 -> 4
faint attack should make contact
detect priority 3 -> 4
endure priority 3 -> 4
rapid spin power 20 -> 50 (gen 8 change)
mirror coat should NOT be affected by mirror move
mirror coat should be affected by protect
psych up should NOT be affected by snatch
ancientpower should NOT make contact
fake out priority 1 -> 3
follow me priority 3 -> 2
taunt should be affected by mirror move
teeter dance should be affected by mirror move
posion fang's bad poison chance 30 -> 50
overheat should NOT make contact
covet should make contact
metal burst should be affected by protect
dragon rush should do extra damage to minimized foes
synchronoise pp 15 -> 10
multi attack power 90 -> 120 (gen 8 change)
double iron bash should deal extra damage to minimized opponents

**Comment by LOuroboros** [comment]
>  metal burst should be affected by protect

Currently taking care of the majority of these as we speak. I wanted to add that Metal Burst should also be affected by Mirror Move.

That's what Bulbapedia says, at least.

**Comment by amiosi** [comment]
small update, I came across a few more:
ally switch priority 1 -> 2
shadow force does NOT deal extra damage to minimize in gen 7+
heavy slam should deal extra damage to minimize
phantom force does NOT deal extra damage to minimize in gen 7+
howl should affect both you and your ally in doubles (gen 8 change)
a few move names are slightly off:
"Sand-Attack" should be "Sand Attack"
"SmokeScreen" should be "Smokescreen"
"Selfdestruct" should be "Self-Destruct", but this is over the 12 character limit
"Softboiled" should be "Soft-Boiled"
"Vice Grip" should be "Vise Grip" (gen 8 change)
"Wake Up Slap" should be "Wake-Up Slap"
"U-Turn" should be "U-turn"
"X Scissor" should be "X-Scissor"
"Roar Of Time" should be "Roar of Time"
"Topsy Turvy" should be "Topsy-Turvy"

**Comment by amiosi** [comment]
I just keep finding more and more obscure things!

whirlwind, roar, mimic, spider web, mean look, block, vital throw, role play, yawn, and skill swap should be set to 0 accuracy (whether it be for display purposes or for actual functionality)
rain dance is NOT a dance move ("rain prayer" in japanese)
seed bomb is a ballistic move
pollen puff is a ballistic move ("pollen ball" in japanese)
beak blast is a ballistic move ("beak cannon" in japanese)
pyro ball is a ballistic move
psychic fangs is boosted by strong jaw
jaw lock is boosted by strong jaw
fishious rend is boosted by strong jaw ("gill bite" in japanese)
ice hammer is boosted by iron fist
plasma fists is boosted by iron fist
double iron bash is boosted by iron fist
howl is a sound based move
magic powder is a powder move

**Comment by amiosi** [comment]
me again!

metronome cannot call: dragon ascent, mind blown, photon geyser, plasma fists
assist cannot call: bounce, phantom force, shadow force, sky drop
assist CAN call: crafty shield
copycat cannot call: spotlight
mimic cannot call: sketch
sleep talk cannot call: freeze shock, ice burn, razor wind, sky attack
