### ISSUE TITLE
Jump Kick into Spiky Shield freezes the game

### ISSUE THREAD

**Issue by BuffelSaft** [DizzyEggg/pokeemerald#488]
If a Pokemon with less than 50% HP uses Jump Kick or High Jump Kick on a target that used Spiky Shield, it'll keep going and crash, which faints it. It then takes damage from Spiky Shield after it's fainted, which locks up the game.

Might be similar issues with Baneful Bunker and King's Shield, but I haven't tested those to confirm yet.

**Comment by DizzyEggg** [comment]
Moved to RHH
