### ISSUE TITLE
X Sp. Def raises Special Attack

### ISSUE THREAD

**Issue by AsparagusEduardo** [DizzyEggg/pokeemerald#490]
Title.
![xspdef](https://user-images.githubusercontent.com/2904965/92670455-6e98d400-f2ea-11ea-810b-2bcbabc584fb.gif)

Also tested on clean item_expansion branch:
![xspdef2](https://user-images.githubusercontent.com/2904965/92670522-98ea9180-f2ea-11ea-8050-f3d4844711ac.gif)

**Comment by Jaizu** [comment]
I looked into this issue and I think I found the problem, even tho I can't fix it.
The item effect is missing here: https://github.com/DizzyEggg/pokeemerald/blob/item_expansion/include/constants/item_effects.h#L15
And if we get that added, it would be nice adding it to the battle_switch_ai as well, there: https://github.com/DizzyEggg/pokeemerald/blob/battle_engine_v2/src/battle_ai_switch_items.c#L883

Let's hope some Egg magician fixes this.

**Comment by LOuroboros** [comment]
I'm giving this a shot since it looks easy enough.

**Comment by AsparagusEduardo** [comment]
Closing, as the issue is now in the RHH fork.

**Comment by AsparagusEduardo** [comment]
https://github.com/rh-hideout/pokeemerald-expansion/issues/14
