### ISSUE TITLE
[battle_engine_v2] Possible regression in multi battles

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#492]
As brought up by @ryuhouji on Discord, multi battles on an up-to-date copy of the battle_engine_v2 are freezing right after your partner and you send out their Pokémon.
https://streamable.com/xr2nae

However, I noticed that it all works normally if I go back to the commit a42bd3f, @DizzyEggg.
https://streamable.com/5hep7y

I suppose the problem may have been caused by one of the following commits: 9a7963e, f70a9ce or 97d0643, since they're the only commits you submitted after commit a42bd3f.

For reference, the tests were done using this script: https://pastebin.com/raw/mGQdvCv9

**Comment by DizzyEggg** [comment]
Moved to RHH
