### ISSUE TITLE
[pokemon_expansion] EVO_MAP should use actual labels and Eevee shouldn't evolve in New Mauville

### ISSUE THREAD

**Issue by LOuroboros** [DizzyEggg/pokeemerald#500]
This issue is more of a reminder to myself than anything else.
Since from what I heard you're currently in the process of merging with upstream, Egg, I decided to hold off on making a PR for now, just in case.

`EVO_MAP` currently uses numerical IDs instead of actual `MAPSEC` labels, which is weird and not intuitive.
On top of that, for whatever reason, Eevee evolves in Leafeon and Glaceon *(though the former takes precedence)* by levelling up in New Mauville if I'm not misunderstanding it, which doesn't really make sense.
Now, the Mossy and Icy Rock evolution methods don't work like `EVO_MAP` does, but there's still more suitable maps to use with the `EVO_MAP` method for these 2, like for example Petalburg Woods and Shoal Cave respectively.

**Comment by DizzyEggg** [comment]
Moved to RHH

**Comment by LOuroboros** [comment]
We already handled this over there actually, we have a method for individual maps, and another one for full map sections :eyes:

https://github.com/rh-hideout/pokeemerald-expansion/blob/pokemon_expansion/src/data/pokemon/evolution.h#L103

https://github.com/rh-hideout/pokeemerald-expansion/blob/pokemon_expansion/src/data/pokemon/evolution.h#L64
