### ISSUE TITLE
Expirence earned from battles stays low

### ISSUE THREAD

**Issue by carpheart** [DizzyEggg/pokeemerald#507]
I'm not sure this is a common issue, but I made it past Watson and halfway into route 111 when I noticed I was still earning about 30 exp per pokemon in trainer battles.

I can't code or anything, but I'll provide any additional information if needed.

**Comment by ExpoSeed** [comment]
Please make issues in https://github.com/rh-hideout/pokeemerald-expansion as that is where active development happens now.

**Comment by carpheart** [comment]
Ok, thank you.
