### ISSUE TITLE
[battle_engine_v2] "Dash" in move descriptions

### ISSUE THREAD

**Issue by sphericalice** [DizzyEggg/pokeemerald#508]
The move descriptions (`src/data/text/move_descriptions.h`) for Flying Press and Freeze-Dry have typos where "FightingDash" and "WaterDash" are written instead of "Fighting-" and "Water-", respectively.

**Comment by LOuroboros** [comment]
The development of feature branches like the battle_engine is now handled by the RHH Organization, fyi.
https://github.com/rh-hideout/pokeemerald-expansion
