### ISSUE TITLE
Roxanne didnt give her badge but the story moved on. 

### ISSUE THREAD

**Issue by Hikari008** [DizzyEggg/pokeemerald#511]
I beat Roxanne and she didnt give her badge. the story DID however continue as if she did. i just cant use HM Cut. talking to her again does nothing. 
![image](https://user-images.githubusercontent.com/83005170/115687384-bcb19380-a31f-11eb-859d-b6d86f5d7901.png)

**Comment by ExpoSeed** [comment]
Couple things:

1. This repo is no longer being worked on. We've moved to https://github.com/rh-hideout/pokeemerald-expansion/
2. Is this an issue with a hack? The sprites in the pic don't look vanilla, and I highly doubt we've touched Roxanne's scripts.
3. If it somehow is an issue with the expansion branches, please specify what branch/branches are affected

**Comment by DizzyEggg** [comment]
Closing per above comment
