### ISSUE TITLE
Update end-of-turn effects to latest gen standards

### ISSUE THREAD

**Issue by Squeetz** [DizzyEggg/pokeemerald#58]
Effects such as Leftovers healing, Sandstorm damage, etc. are executed after the switch-in queue instead of _before_ Pokémon switch in, the latter being the case in later generations.

Also update the behavior where Pokémon switch in prematurely. Example:
Battler A chooses Quiver Dance
Battler B is faster, chooses Double-Edge
Battler B damages Battler A but knocks itself out in the process due to recoil
Battler B then immediately switches in a new Pokémon, cancelling Battler A's Quiver Dance
In later generations, the defending Pokémon's action executes regardless of the opponent's presence.
(Exception: If the opponent has no more Pokémon in their party, cancel action)

**Comment by Squeetz** [comment]
Tip: look into HandleFaintedMonActions as it's what runs BattleScript_HandleFaintedMon
<https://github.com/pret/pokeemerald/blob/d2c17c7fb3ba6149b4e278bd3b644cd4d4d240e2/src/battle_util.c#L1262>

**Comment by DizzyEggg** [comment]
143cb7ad3
