### ISSUE TITLE
Charge Beam's Effect Is Incorrect

### ISSUE THREAD

**Issue by Kurausukun** [DizzyEggg/pokeemerald#60]
Charge Beam is supposed to deal damage with a chance of raising Special Attack; right now it just boosts Special Attack without dealing damage.

EDIT: I haven't tested it, but looking at how it's defined, I think Fiery Dance has the same issue. Additionally, I have determined that this issue stems from the fact that there is no EFFECT_SPECIAL_ATTACK_UP effect defined (there were no moves that dealt damage and raised Special Attack in Gen 3, so this will need to be added).

**Comment by DizzyEggg** [comment]
88b788bfa
