### ISSUE TITLE
Fix Psycho Shift

### ISSUE THREAD

**Issue by Squeetz** [DizzyEggg/pokeemerald#69]
at <https://github.com/DizzyEggg/pokeemerald/blob/battle_engine_v2/src/battle_script_commands.c#L7058>
should be:
gBattleMons[gBattlerTarget].status1 = gBattleMons[gBattlerAttacker].status1 & STATUS1_ANY;
as to not copy the toxic counter (0xF00)

**Comment by DizzyEggg** [comment]
40e1dcb1d
