### ISSUE TITLE
Need documentation & Graphic bug learning move on battle.

### ISSUE THREAD

**Issue by jmwielandt** [DizzyEggg/pokeemerald#79]
Category image still when switching to contest data.

![pokeemerald-0](https://user-images.githubusercontent.com/37153467/53281038-1b0f6700-3701-11e9-885c-28b58e50108c.png)
![pokeemerald-1](https://user-images.githubusercontent.com/37153467/53281039-1b0f6700-3701-11e9-8a20-6e654ba48362.png)

Also... how can i manage double wild battles?

**Comment by DizzyEggg** [comment]
b0f46c68b

src/wild_encounter.c line 585

Many people asked me about this, so I guess I'll include this information on PC's thread.
