### ISSUE TITLE
Move Reminder Display Errors

### ISSUE THREAD

**Issue by ultima-soul** [DizzyEggg/pokeemerald#95]
There seems to be strange errors in how the move description and stuff are displayed for the Move Reminder in Fallarbor Town

![pokeemerald-1](https://user-images.githubusercontent.com/33333039/53677130-f7e43a80-3c5f-11e9-9046-776c1fca3b64.png)
![pokeemerald-2](https://user-images.githubusercontent.com/33333039/53677131-f7e43a80-3c5f-11e9-94dd-e74cccdc65be.png)
![pokeemerald-0](https://user-images.githubusercontent.com/33333039/53677132-f7e43a80-3c5f-11e9-809a-2bcf7b4bd983.png)

**Comment by DizzyEggg** [comment]
Caused by a un-decompiled function referencing gBattleMoves whose struct definition was changed.
c9c38024e
